### ISSUE TITLE
[Bug]: Import: Unable to read MonoBehaviour, because script layout MeshCombiner mismatch binary content

### ISSUE THREAD

**Issue by Th3Nigh7mare** [AssetRipper/AssetRipper#300] opened 2022-03-08 11:13 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

version 2019.4.31.12409535 (phasmophobia)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

In the console version windows x64 GUI:

Import : Resource file 'sharedassets11.assets.resS' has been loaded
Import : Resource file 'level1.resS' has been loaded
Import : Resource file 'level10.resS' has been loaded
Import : Resource file 'level11.resS' has been loaded
Import : Unable to read MonoBehaviour, because script layout MeshCombiner mismatch binary content
Import : Resource file 'level2.resS' has been loaded
Import : Resource file 'level3.resS' has been loaded
**Import : Unable to read MonoBehaviour, because script layout MeshCombiner mismatch binary content**
Import : Resource file 'level4.resS' has been loaded
Import : Resource file 'level5.resS' has been loaded
Import : Resource file 'level6.resS' has been loaded
**Import : Unable to read MonoBehaviour, because script layout MeshCombiner mismatch binary content**
Import : Resource file 'level7.resS' has been loaded
Import : Resource file 'level8.resS' has been loaded
Import : Resource file 'level9.resS' has been loaded
**Import : Unable to read MonoBehaviour, because script layout MeshCombiner mismatch binary content**
General : Finished reading files
 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8205617/AssetRipper.log)

**Comment by ds5678** [comment] 2022-03-08 11:18
I'm currently on mobile, so I can't look at the log right now. However, unless there's a whole bunch of these, it's normal.

Duplicate of #229

**Comment by ds5678** [comment] 2022-03-08 17:58
I just took a look at the log. If there were dozens of these, it might be concerning, but a single MonoBehaviour being mismatched is normal.

**Closed by ds5678** 2022-03-08 17:58 UTC
Labels: bug
