### ISSUE TITLE
[Question]: How do i get from exported files back the normal files?

### ISSUE THREAD

**Issue by StudioTeamTV** [AssetRipper/AssetRipper#1331] opened 2024-05-04 13:33 UTC
### Question

When i export all the files it works, but how do i get from exported files back the normal files (like sharedassets0.assets)
1. Without using unity
2. or help with openning the files in unity **WITHOUT** errors (i have same version of unity the game is using)

### Are you sure you want to clutter the issues section?

No, I need to use the discussions tab. I will recieve better support there.

**Comment by ds5678** [comment] 2024-05-04 14:05
Duplicate of #1122

**Closed by ds5678** 2024-05-04 14:05 UTC
