### ISSUE TITLE
[Bug]: Throws "No Data left" after 10% exporting

### ISSUE THREAD

**Issue by ColdRogue26** [AssetRipper/AssetRipper#597] opened 2022-11-04 18:40 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Star Trek FLeet Command

### Which Unity version did this occur on?

2020.3.18.337902

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

While exporting the data of the game directory, around 25k files, the Export always stops at around 5k files and always after the same file (See the log). I have attempted to input data from another unity-directory for the game which then caused the same error after a different file.
I am unsure why the program reports "No data left" especially if other asset files of the same kind as the last exported ones are still to be exported. 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9941172/AssetRipper.log)

**Comment by ds5678** [comment] 2022-11-06 22:11
Duplicate of #281

**Closed by ds5678** 2022-11-06 22:11 UTC
Labels: bug
