### ISSUE TITLE
[Bug]: AssetRipper uses an unreasonable amount of RAM

### ISSUE THREAD

**Issue by ggtylerr** [AssetRipper/AssetRipper#370] opened 2022-05-05 01:25 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.33f

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When loading a folder, the app uses an excessive amount of RAM.
![Taskmgr_qjH8CyrcGY](https://user-images.githubusercontent.com/28498877/166851453-1f6c41b6-2912-4306-82fc-c0471a31b90a.png)
*Note: It jumped up to 9GB before I had to close it.*

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8628273/AssetRipper.log)

**Comment by ds5678** [comment] 2022-05-08 15:22
Although resource management is always on my mind, making substantial improvements is very hard. This should be slightly improved by #164.

Duplicate of #94 and #185

**Closed by ds5678** 2022-05-08 15:22 UTC
Labels: bug
