### ISSUE TITLE
[Other]: Need help with script extracting

### ISSUE THREAD

**Issue by Darklaser38** [AssetRipper/AssetRipper#1005] opened 2023-08-25 14:55 UTC
### Describe the issue

Hello i got a problem. So i can't extract the script from the assetbundle that i want to. The game is an android game based on IL2Cpp. Here the log.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12440704/AssetRipper.log)

**Comment by ds5678** [comment] 2023-08-25 15:00
I assume it crashes?

**Comment by Darklaser38** [comment] 2023-08-25 15:02
No its just that the script are dummy script

**Comment by Darklaser38** [comment] 2023-08-25 15:03
[script.txt](https://github.com/AssetRipper/AssetRipper/files/12440769/script.txt)

**Comment by ds5678** [comment] 2023-08-25 15:09
Duplicate of #655

**Closed by ds5678** 2023-08-25 15:09 UTC
