### ISSUE TITLE
[Bug]: Cecil Resolution Error

### ISSUE THREAD

**Issue by Bunie89** [AssetRipper/AssetRipper#416] opened 2022-06-02 13:49 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

VRChat
https://steamdb.info/app/438100/

### Which Unity version did this occur on?

2019.4.31f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Since this Commit (linked Below), Upon attempting extraction, AssetRipper fails upon not finding a "UnityEditor.dll" Which was never needed before and doesn't seem to exist for this context. Worked fine in 2.0.2 stable and below.

https://github.com/AssetRipper/AssetRipper/commit/2e0ae39d41c17e94fc92119233869cc899325381

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22000.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.2.0.3
System : AssetRipper Build Type: Release x64 Compiled
System : UTC Current Time: 6/2/2022 11:57:37 AM
System : UTC Compile Time: Wed May 25 04:13:57 UTC 2022
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Bunie\source\repos\AssetRipper\Bins\AssetRipperGUI\ReleaseWindows\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: DllExportWithoutRenaming
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from 2 paths...
Import : Game file 'bean.vrca' has been found
Import : Mixed game structure has been found for 2 paths
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 143 assemblies
General : Finished reading files
General : About to begin export to F:\Temp\Ripz\bean.vrca
General : Removing any files from a previous export...
Export : Attempting to export assets to F:\Temp\Ripz\bean.vrca...
Import [Warning] : Assembly 'UnityEditor' hasn't been found
[Error] : Mono.Cecil.ResolutionException: Failed to resolve UnityEditor.ShortcutManagement.ShortcutModifiers
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver.CreatePEFile(AssemblyDefinition assembly) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 41
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(ReadOnlySpan`1 assemblies) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 19
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(IAssemblyManager manager) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 14
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler..ctor(IAssemblyManager assemblyManager) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 18
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter..ctor(IAssemblyManager assemblyManager, LibraryConfiguration configuration) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 28
   at AssetRipper.Library.Ripper.OverrideNormalExporters() in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 268
   at AssetRipper.Library.Ripper.InitializeExporters() in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 219
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 152
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperLibrary\Ripper.cs:line 141
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in C:\Users\Bunie\source\repos\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 52

**Comment by Bunie89** [comment] 2022-06-02 14:14
I've been told it's important to mention some extra information on this issue:
Some of the assemblies i use are from the games SDK, as well as some generated by Unity's Editor. (\Library\ScriptAssemblies)
This is because of the games user content is generated from different SDKs and would missmatch otherwise, preventing me from  getting some of the monoscript content.

**Comment by ds5678** [comment] 2022-08-17 13:43
Duplicate of #227

**Closed by ds5678** 2022-08-17 13:43 UTC
Labels: bug, export, upstream, scripts
