### ISSUE TITLE
[Bug]: Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content

### ISSUE THREAD

**Issue by Clara81221** [AssetRipper/AssetRipper#1061] opened 2023-10-10 01:38 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Cooking Simulator 2 Demo](https://steamdb.info/app/2455360/)

### Which Unity version did this occur on?

2021.3.20

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

`Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content`
Errors in log. no idea what it means but thought i'd report it

### Relevant log output

[AssetRipper - Copy.log](https://github.com/AssetRipper/AssetRipper/files/12851852/AssetRipper.-.Copy.log)

**Comment by ds5678** [comment] 2023-10-26 11:08
I was unable to acquire the demo, but this is likely #698.

**Comment by ds5678** [comment] 2023-11-07 04:08
I'm closing this because I can't test and because it's likely a duplicate of the other issue. Feel free to reopen if either of these reasons becomes no longer valid.

**Closed by ds5678** 2023-11-07 04:08 UTC
Labels: bug
