### ISSUE TITLE
[Bug]: Segmentation fault while trying to unpack unity crunch

### ISSUE THREAD

**Issue by Kyr4l** [AssetRipper/AssetRipper#1378] opened 2024-06-03 14:18 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

[private project ; can't mention the game name]

### Which Unity version did this occur on?

2021.33.33f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

unpacking all files ends up with the following error :
```
[...]
ExportProgress : Exporting 'foo-bar'
About to unpack unity crunch...
Segmentation fault (core dumped)

```

**Comment by Kyr4l** [comment] 2024-06-03 14:38
tested the same thing on a windows VM, no error whatsoever
so that's a linux build bug

**Comment by ds5678** [comment] 2024-06-09 00:25
Duplicate of #448

**Closed by ds5678** 2024-06-09 00:25 UTC
Labels: bug
