### ISSUE TITLE
[Bug]: Mono.Cecil failure

### ISSUE THREAD

**Issue by githubexplorer2342** [AssetRipper/AssetRipper#463] opened 2022-07-14 13:08 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://steamdb.info/app/1205040/

### Which Unity version did this occur on?

2019.2.11f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

In previous version of AssetRipper, i was able to export the game with no issue, but in the latest version, it gives me an error when i try to export all files.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9111998/AssetRipper.log)

**Comment by ds5678** [comment] 2022-07-14 13:12
Duplicate of #227

**Closed by ds5678** 2022-07-14 13:12 UTC
Labels: bug
