### ISSUE TITLE
I have this problem. Please help me with this

### ISSUE THREAD

**Issue by artem3601** [AssetRipper/AssetRipper#558] opened 2022-09-29 05:47 UTC
### Describe the issue

`Error during reading of asset type MonoBehaviour. V: 4.7.2f1 P: Android N: level34 Path: C:\Users\artem\AppData\Local\Temp\Rar$EXa10228.48359\temp\300ed10a22\assets\bin\Data\level34
System.BadImageFormatException: Could not read C:\Users\artem\AppData\Local\Temp\Rar$EXa10228.48359\temp\300ed10a22\assets\bin\Data\Managed\Assembly-CSharp.dll ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at AssetRipper.Core.Structure.Assembly.Managers.BaseManager.Load(String filePath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\Assembly\Managers\BaseManager.cs:line 65
   at AssetRipper.Core.Structure.Assembly.Managers.BaseManager.Load(String filePath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\Assembly\Managers\BaseManager.cs:line 65
   at AssetRipper.Core.Structure.GameStructure.GameStructure.OnRequestAssembly(String assembly) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 227
   at AssetRipper.Core.Structure.Assembly.Managers.BaseManager.FindAssembly(String name) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\Assembly\Managers\BaseManager.cs:line 272
   at AssetRipper.Core.Structure.Assembly.Managers.BaseManager.FindType(String assembly, String namespace, String name) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\Assembly\Managers\BaseManager.cs:line 298
   at AssetRipper.Core.Structure.Assembly.Managers.BaseManager.GetScriptID(String assembly, String namespace, String name) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\Assembly\Managers\BaseManager.cs:line 193
   at AssetRipper.SourceGenerated.Helpers.MonoScriptHelper.GetBehaviourType(IUnityObjectBase monoScript, String originalAssemblyName, String namespace, String class)
   at AssetRipper.SourceGenerated.Helpers.MonoBehaviourHelper.ReadStructureInjected(IUnityObjectBase monoScript, Utf8StringBase originalAssemblyName, Utf8StringBase namespace, Utf8StringBase className, AssetReader reader, Utf8StringBase monoScriptName, Utf8StringBase monoBehaviourName)
   at AssetRipper.SourceGenerated.Helpers.MonoBehaviourHelper.MaybeReadStructure(IMonoBehaviour monoBehaviour, AssetReader reader)
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadAsset(AssetReader reader, AssetInfo assetInfo, Int64 offset, Int32 size) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 321`

**Comment by ds5678** [comment] 2022-09-29 14:20
Duplicate of #227

**Closed by ds5678** 2022-09-29 14:20 UTC
