### ISSUE TITLE
[Bug]:  System.FormatException: Invalid or corrupt metadata (magic number check failed)

### ISSUE THREAD

**Issue by tomh520** [AssetRipper/AssetRipper#1341] opened 2024-05-13 10:55 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Game: Rumble-Heroes.apk
Link: https://play.google.com/store/apps/details?id=com.playhardlab.heroes&hl=en_US

### Which Unity version did this occur on?

2021.3.26f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Import : Collecting game files...
Import : Asset bundle 'data.unity3d' has been found
Import : Files use the 'IL2Cpp' scripting backend.
Import : During Il2Cpp initialization, found Unity version: 2021.3.26f1
Cpp2IL : Initializing Metadata...
Import : Could not initialize assembly manager. Switching to the 'Unknown' scripting backend.
Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.FormatException: Invalid or corrupt metadata (magic number check failed)
   at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[], UnityVersion) + 0x449
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[], Byte[], UnityVersion) + 0x89
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean) + 0x89
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean) + 0x12c
   at AssetRipper.Import.Structure.Assembly.Managers.IL2CppManager.Initialize(PlatformGameStructure) + 0x196
   at AssetRipper.Import.Structure.GameStructure.InitializeAssemblyManager(CoreConfiguration) + 0x27d

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15293295/AssetRipper.log)

**Comment by ds5678** [comment] 2024-05-13 16:01
Duplicate of https://github.com/SamboyCoding/Cpp2IL/issues/281

**Closed by ds5678** 2024-05-13 16:01 UTC
Labels: bug
