### ISSUE TITLE
[Other]: Specifying an arbitrary Unity version?

### ISSUE THREAD

**Issue by marlangcom** [AssetRipper/AssetRipper#874] opened 2023-06-26 00:05 UTC
### Describe the issue

It seems that there is a need for a function that allows users to write down and use a Specifying version instead of a modified asset used in a specific game or a version that has been deleted from a bundle file.
In the case of bundle files of PROJECT SEKAI, the Unity version is marked as 0.0.0

UnityFS   5.x.x   0.0.0
The actual game version is 2020.3.32f1.

[sample file (xor decrypted)](https://drive.google.com/file/d/1_krOi7zqJlP22hdwm5wJ1dwdskamqn19/view?usp=sharing
)

--- log ---

System.ArgumentOutOfRangeException: File index cannot be negative: -109663400 (Parameter 'fileIndex')
   at AssetRipper.Assets.Collections.AssetCollection.ThrowIfFileIndexOutOfRange(Int32 fileIndex) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Collections\AssetCollection.cs:line 316
   at AssetRipper.Assets.Collections.AssetCollection.TryGetAsset(Int32 fileIndex, Int64 pathID, IUnityObjectBase& asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Collections\AssetCollection.cs:line 263
   at AssetRipper.Assets.Collections.AssetCollection.TryGetAsset(Int32 fileIndex, Int64 pathID) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Collections\AssetCollection.cs:line 251
   at AssetRipper.Assets.Metadata.PPtrExtensions.TryGetAsset[T](IPPtr`1 pptr, IAssetContainer file, T& asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Metadata\IPPtr.cs:line 67
   at AssetRipper.Assets.Metadata.PPtrExtensions.TryGetAsset[T](IPPtr`1 pptr, IAssetContainer file) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Metadata\IPPtr.cs:line 87
   at AssetRipper.Assets.Generics.PPtrAccessList`2.get_Item(Int32 index) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Generics\PPtrAccessList.cs:line 33
   at AssetRipper.Assets.Generics.PPtrAccessList`2.GetEnumerator()+MoveNext() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Generics\PPtrAccessList.cs:line 84
   at AssetRipper.SourceGenerated.Extensions.GameObjectExtensions.TryGetComponent[T](IGameObject gameObject, T& component) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.SourceGenerated.Extensions\GameObjectExtensions.cs:line 124
   at AssetRipper.Processing.PrefabProcessor.Process(GameBundle gameBundle, UnityVersion projectVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\PrefabProcessor.cs:line 29
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 123
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20

**Comment by ds5678** [comment] 2023-06-26 18:44
Duplicate of #252

**Closed by ds5678** 2023-06-26 18:44 UTC
