### ISSUE TITLE
[Enhancement]: Skip errors and show the name of the source file being unpacked when exporting

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#465] opened 2022-07-16 07:17 UTC
### Describe the new feature or enhancement

I can load all the game files smoothly, but for the error, when exporting, the error "No data left" is reported. There are 30000+ game files. I am not sure which file is reporting the error. I hope, I can skip the error and continue to execute, or display the error message file name. It can also display which file is being unpacked, so that it is convenient to find the error file and delete it.
![1](https://user-images.githubusercontent.com/58507193/179344622-2a5f75e2-8abf-4bb8-9480-1113fb5cf43e.JPG)

**Comment by ds5678** [comment] 2022-07-19 02:02
Duplicate of #281

**Closed by ds5678** 2022-07-19 02:02 UTC
Labels: enhancement
