### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kaleidoscopess** [AssetRipper/AssetRipper#440] opened 2022-06-20 17:58 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://steamdb.info/app/1970020/

### Which Unity version did this occur on?

2021.3.3f1
From the game log file:"Initialize engine version: 2021.3.3f1 (af2e63e8f9bd)"

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I tried to load the bundle file of the game but got an error: "System.Exception: Incorrect number of bytes written. -1 instead of 131072". But assets and levels can be loaded normally. I initially suspected that it might be encrypted, but AssetStudio can extract it correctly.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8942780/AssetRipper.log)

**Comment by ds5678** [comment] 2022-06-20 18:31
duplicate of #382

**Closed by ds5678** 2022-06-20 18:31 UTC
Labels: bug, duplicate, import
