### ISSUE TITLE
Addition of Visual Element to See What Is Going On When Exporting [Enhancement]: 

### ISSUE THREAD

**Issue by ColdSteel503** [AssetRipper/AssetRipper#266] opened 2022-02-16 17:27 UTC
### Describe the new feature or enhancement

I have noticed that when trying to "export all" for larger files, the program will hang on "preparing to export". CPU usage would remain at 3.5% just for the program on an 3950x cpu with my RAM reaching around 56Gb. It _seems_ like it is doing something but I simply do not know what. I had left the program running for about 10 hours but no visuals changed; I ultimately closed the program assuming it had stopped working.

I think having a step-by-step log in the console to show what the program is doing _while_ "preparing to export" would give me peace of mind that the program is doing as intended and has not stopped working all together.

**Comment by ds5678** [comment] 2022-02-16 17:45
There is a regression in `0.1.9.2` where asset dependency checking takes n squared time before exporting commences. It has since been resolved and will be part of `0.1.9.3` which will be released soon. Additionally you can get the fix immediately from the alpha build download links.

**Closed by ds5678** 2022-02-16 17:45 UTC
Labels: enhancement

**Comment by ColdSteel503** [comment] 2022-02-16 17:49
> Which game is this and which version of ripper are you using? There _was_ a bug, a long time ago, where this was an issue, but I fixed it. Preparing to export should take a handful of seconds, at most.

The game is Escape From Tarkov, version 12.12.  

> There is a regression in `0.1.9.2` where asset dependency checking takes n squared time before exporting commences. It has since been resolved and will be part of `0.1.9.3` which will be released soon. Additionally you can get the fix immediately from the alpha build download links.

Oh I see, I'll go ahead and download the alpha build. Thank you!
