### ISSUE TITLE
[Bug]: Errors when ripping UnityWebPlayer games

### ISSUE THREAD

**Issue by BART117** [AssetRipper/AssetRipper#1065] opened 2023-10-13 13:50 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Every UnityWebPlayer game. 

### Which Unity version did this occur on?

4.5.0f6
4.3.4f1
4.5.4f1
4.0.1f2
4.3.2f1
4.6.9f1
5.1.1f1
And much more 
i think it doesnt matter 

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

exported scripts contains only "Dummy class. This could have happened for several reasons:" blablabla...

Log always contains 

Import : Files use the 'Unknown' scripting backend.
Import : Dependency 'library/unity default resources' wasn't found
And 
Import : Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content (ArgumentOutOfRangeException).
Import : Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content (ArgumentOutOfRangeException).
(SOMETIMES DONT SHOW) but still no code

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12893842/AssetRipper.log)

**Comment by ds5678** [comment] 2023-10-13 13:56
Am I correct that `special-strike-dust-2.unity3d` is almost the entire game and that the assemblies are embedded inside it?

**Comment by BART117** [comment] 2023-10-13 14:02
> Am I correct that `special-strike-dust-2.unity3d` is almost the entire game and that the assemblies are embedded inside it?

YES

**Comment by BART117** [comment] 2023-10-13 18:20
> Is this different from #928 ?

UnityWebPlayer games are in .unity3d files not unityweb ?

**Comment by ds5678** [comment] 2023-10-13 18:21
But your problem only comes from the assemblies being inside the bundle, correct?

**Comment by BART117** [comment] 2023-10-13 18:22
> But your problem only comes from the assemblies being inside the bundle, correct?

yes

**Comment by ds5678** [comment] 2023-10-13 18:22
Then it's a duplicate

**Comment by ds5678** [comment] 2023-10-13 18:22
Duplicate of #928

**Closed by ds5678** 2023-10-13 18:22 UTC
Labels: bug
