### ISSUE TITLE
[Bug]: UNKNOWN ERROR

### ISSUE THREAD

**Issue by josiauh** [AssetRipper/AssetRipper#999] opened 2023-08-22 02:06 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

PolarChase on the Oculus Store

### Which Unity version did this occur on?

2021.1.23f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I ripped the game [(here's a link for it)](https://www.oculus.com/experiences/quest/5617930194981532/) [(and the apk link)](https://securecdn.oculus.com/binaries/download/?id=6346510575456820) and i get an error that is called "UNKNOWN" in the crash logs and later in the logs it comes out as a SIGSEV, which i had sufficient memory to use. [Editor.log](https://github.com/AssetRipper/AssetRipper/files/12403944/Editor.log) for reference.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12403934/AssetRipper.log)

**Comment by ds5678** [comment] 2023-08-22 14:29
Duplicate of #795

**Closed by ds5678** 2023-08-22 14:29 UTC
Labels: bug
