### ISSUE TITLE
[Bug]: Windows Mode "Dark" + App mode "Light" = Black text on a dark screen

### ISSUE THREAD

**Issue by GregariousJB** [AssetRipper/AssetRipper#1150] opened 2024-01-06 04:10 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

N/A

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

![https://i.imgur.com/33iu8uP.png](https://i.imgur.com/33iu8uP.png)

Whew. For a minute there I thought this was the default look of the program, then I figured I'd mess around with the color settings in Windows. 

![https://i.imgur.com/XpAjViI.png](https://i.imgur.com/XpAjViI.png)

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Sat Jan  6 03:51:38 UTC 2024
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json

**Comment by ds5678** [comment] 2024-01-06 04:25
Duplicate of #797

**Closed by ds5678** 2024-01-06 04:25 UTC
Labels: bug
