### ISSUE TITLE
[Bug]: Error: "Specified Cast is Invalid"

### ISSUE THREAD

**Issue by brokirkoo** [AssetRipper/AssetRipper#543] opened 2022-09-14 22:56 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

GTFO
https://steamdb.info/app/493520/

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

In the console, when trying to export:

System.InvalidCastException: Specified cast is not valid

![](https://cdn.discordapp.com/attachments/1007332452412428359/1019741374058348584/unknown.png)

**Comment by brokirkoo** [comment] 2022-09-14 22:57
Can't access the AssetRipper.log unfortunately, don't have the time to now. Hopefully the screenshot is sufficient, my apologies.

**Comment by ds5678** [comment] 2022-09-14 23:00
Duplicate of #227

**Closed by ds5678** 2022-09-14 23:00 UTC
Labels: bug
