### ISSUE TITLE
[Other]: DllNotFoundException VivoxNative

### ISSUE THREAD

**Issue by mitakabg20** [AssetRipper/AssetRipper#1594] opened 2024-12-12 19:25 UTC
### Describe the issue

I decompiled a multiplayer game from 2018 called Secret Neighbor Christmas Alpha. But i keep getting this issue, and the game isn't even loading.
![Screenshot 2024-12-12 212318](https://github.com/user-attachments/assets/58436401-8884-4459-99ab-c1446d304c6a)
![Screenshot 2024-12-12 212329](https://github.com/user-attachments/assets/782e8a8d-bd7c-4362-95ea-f03709bf5eb5)

**Comment by ds5678** [comment] 2024-12-12 19:33
Duplicate of #924

**Closed by ds5678** 2024-12-12 19:33 UTC
