### ISSUE TITLE
[Bug]: Unable to decompress crunched texture

### ISSUE THREAD

**Issue by Wolfskii** [AssetRipper/AssetRipper#672] opened 2023-01-02 14:53 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

VRChat

### Which Unity version did this occur on?

Unity 2019.4.31f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Crashes when exporting all files with Enable Prefab Outlining and Enable Static Mesh Separation ticked.

### Relevant log output

ExportedFile : 'ReflectionProbe-8' exported
System.Exception: Unable to decompress crunched texture
   at AssetRipper.Library.Exporters.Textures.CrunchHandler.DecompressCrunchWithUtinyDecoder(TextureFormat textureFormat, Int32 width, Int32 height, UnityVersion unityVersion, ReadOnlySpan`1 data) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\CrunchHandler.cs:line 67
   at AssetRipper.Library.Exporters.Textures.TextureConverter.ConvertToBitmap(TextureFormat textureFormat, Int32 width, Int32 height, Int32 depth, Int32 imageSize, UnityVersion version, Byte[] data) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\TextureConverter.cs:line 96
   at AssetRipper.Library.Exporters.Textures.TextureConverter.ConvertToBitmap(ITexture2D texture) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\TextureConverter.cs:line 46
   at AssetRipper.Library.Exporters.Textures.TextureAssetExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\TextureAssetExporter.cs:line 60
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\Collections\AssetExportCollection.cs:line 26
   at AssetRipper.Core.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 271
   at AssetRipper.Core.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 177
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 84
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 159
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 141
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIExportManager.cs:line 52

**Comment by ds5678** [comment] 2023-02-21 17:16
Duplicate of #735

**Closed by ds5678** 2023-02-21 17:16 UTC
Labels: bug
