### ISSUE TITLE
[Bug]: Invalid version format

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#777] opened 2023-03-26 07:45 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://tlbb2.qq.com/

### Which Unity version did this occur on?

2019.4.40f1c1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Versions after 3.0.5 have this error, Invalid version format: 2019.4.40f1c1
[FX_EMei_Skill4_XinFa01_prefab.zip](https://github.com/AssetRipper/AssetRipper/files/11071018/FX_EMei_Skill4_XinFa01_prefab.zip)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11071017/AssetRipper.log)

**Comment by ds5678** [comment] 2023-03-27 01:12
Duplicate of #759

**Closed by ds5678** 2023-03-27 01:12 UTC
Labels: bug

**Comment by Q4st** [comment] 2023-03-29 09:27
@ds5678 
When I try again, I get two errors, including the GUID issue raised last time, both errors crash AssetRipper, exiting！

[Uploading Error1.txt…]()

The GUID error problem is that when all files are loaded, an error will be reported. If these files are loaded separately, everything is normal
[Error1File.zip](https://github.com/AssetRipper/AssetRipper/files/11098813/Error1File.zip)

The second error is that when there is an error in the file itself, AssetRipper will crash instead of an error message！

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11098878/AssetRipper.log)
[Error2File.zip](https://github.com/AssetRipper/AssetRipper/files/11098882/Error2File.zip)
