### ISSUE TITLE
Textures Breaking With Static Mesh Sepration

### ISSUE THREAD

**Issue by AvalonMods** [AssetRipper/AssetRipper#703] opened 2023-01-20 14:30 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Capuchin (https://www.oculus.com/experiences/quest/5409297455797322/) (.apk)

### Which Unity version did this occur on?

2021.3.14f

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

ripped Fine, But a few textures were broken, and glitched.

**Comment by ds5678** [comment] 2023-01-20 14:32
This sounds like a duplicate of #683

**Comment by ds5678** [comment] 2023-01-20 14:49
Do you have any reason to believe it's not?

**Comment by ds5678** [comment] 2023-01-21 14:51
Duplicate of #683

**Closed by ds5678** 2023-01-21 14:51 UTC
Labels: bug
