### ISSUE TITLE
[Bug]: Read 4004 decompling shader

### ISSUE THREAD

**Issue by JeanAU** [AssetRipper/AssetRipper#1000] opened 2023-08-22 10:44 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Among Us old version

### Which Unity version did this occur on?

2020.3.7f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

when i open assetripper and choose the apk i get errors

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12407923/AssetRipper.log)

**Comment by ds5678** [comment] 2023-08-22 14:27
Duplicate of #595

**Closed by ds5678** 2023-08-22 14:27 UTC
Labels: bug
