### ISSUE TITLE
[Enhancement]: Manually entering Unity version when it cannot be identified

### ISSUE THREAD

**Issue by MiddleRed** [AssetRipper/AssetRipper#948] opened 2023-07-26 15:51 UTC
### Describe the new feature or enhancement

To anti-reverse asset bundles, some will strip the Unity version in its header, so it will be helpful to provide an option to enter the correct Unity version manually

**Comment by ds5678** [comment] 2023-07-26 21:47
Duplicate of #252

**Closed by ds5678** 2023-07-26 21:47 UTC
Labels: enhancement
