### ISSUE TITLE
[Bug]: My Desktop is DELETED

### ISSUE THREAD

**Issue by ColorBuffer** [AssetRipper/AssetRipper#1177] opened 2024-01-30 06:18 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

badnorth

### Which Unity version did this occur on?

2018.4.0

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

with default options I selected my desktop as desnation. then export

then an error occured (forgot to save it)

then I looked at my desktop

It's gone.

never ask me about recovery

**Comment by DavidLeBonk** [comment] 2024-01-30 09:52
This is going to frustrate you but it is not a bug, it's the nature of how asset ripper extract. The folder being extracted to is wiped before extracted files are placed. What likely happened here was the folder was wiped and then it errored while extracting leaving it all empty. Newer (pre releases) have warnings when extracting that the target folder will be erased before extract but the version used here didn't have these warnings. It's known and I know you mentioned not wanting to hear about recovering but if nothing was extracted after deletion there is a **very** good chance your files can be recovered and it's your best bet to recover.

**Comment by aWZHY0yQH81uOYvH** [comment] 2024-02-01 16:33
My desktop is also now deleted. Not the best design decision to wipe the destination folder without any prompt or suggestion of what it's going to do, especially as this is probably the first thing a user is going to do. Thankfully it deleted itself so it won't happen again.

**Comment by ds5678** [comment] 2024-02-01 17:09
Duplicate of #1163

**Closed by ds5678** 2024-02-01 17:09 UTC
Labels: bug

**Comment by ordylan** [comment] 2024-02-02 10:36
It's true!!
