### ISSUE TITLE
[Bug]: Exported AudioClip WAV files don't load in Unity

### ISSUE THREAD

**Issue by TheInfinityUser** [AssetRipper/AssetRipper#840] opened 2023-05-31 10:40 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Pixel Gun 3D (23.3.2 - latest version as of now)
https://play.google.com/store/apps/details?id=com.pixel.gun3d&hl=en&gl=US

### Which Unity version did this occur on?

2021.3.14f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I exported only the obb file. I have attached a Google Drive link for the obb, if that helps.
[https://drive.google.com/file/d/16jVqyjQ61LuSy_yZVEZfxX1DIasCXIID/view?usp=sharing](url)
Despite numerous errors highlighted red that I got in the console, most of the files exported correctly. However, the wav AudioClip files cannot be played by Media Player but interestingly can be played on Chrome and Discord, when I upload them. When I import even one of the wav files to Unity, I get this error,
```
Errors during import of AudioClip Assets/Weapons1.wav:
FSBTool ERROR: The format of the source file is invalid, see output for details.
FSBTool ERROR: Internal error from FMOD sub-system.
```
I tried ffprobe on the wav file and I got the following,
```
[wav @ 000002096b740900] Packet corrupt (stream = 0, dts = NOPTS).
[wav @ 000002096b740900] Estimating duration from bitrate, this may be inaccurate
Input #0, wav, from 'Adamant Sniper Rifle_shoot.wav':
Duration: 00:00:01.62, bitrate: 705 kb/s
Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 1 channels, s16, 705 kb/s]
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11611899/AssetRipper.log)

**Comment by ds5678** [comment] 2023-05-31 12:55
Not AssetRipper's fault.
https://github.com/SamboyCoding/Fmod5Sharp

**Comment by ds5678** [comment] 2023-07-02 21:41
Duplicate of https://github.com/SamboyCoding/Fmod5Sharp/issues/9

**Closed by ds5678** 2023-07-02 21:41 UTC
Labels: bug
