### ISSUE TITLE
[Bug]: Unable to read MonoBehaviour Structure, because script Base layout mismatched binary content

### ISSUE THREAD

**Issue by NotNite** [AssetRipper/AssetRipper#1019] opened 2023-09-03 23:26 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Bomb Rush Cyberfunk ([Steam](https://store.steampowered.com/app/1353230/Bomb_Rush_Cyberfunk/), [GOG](https://www.gog.com/en/game/bomb_rush_cyberfunk), [SteamDB](https://steamdb.info/app/1353230/)), title screen version "1.0.19864"

### Which Unity version did this occur on?

2021.3.27f1 (2021.3.27.16379, ca3ffb99bcc6)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When opening the game in AssetRipper, the log is spammed with these messages (over 700+ log lines).

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12508135/AssetRipper.log)

**Comment by ds5678** [comment] 2023-09-04 00:40
Without looking, it's probably #698

**Comment by ds5678** [comment] 2023-09-19 16:11
I verified that this is not #698. The game does not use [SerializeReference] for anything.

**Comment by elirnm** [comment] 2023-10-04 04:51
This also happens with [Pentiment](https://steamdb.info/app/1205520/)(tried with game version 1.2.1716, Unity 2021.3.23f1, IL2Cpp)

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12799382/AssetRipper.log)

**Comment by ds5678** [comment] 2023-10-26 10:55
I verified that this is indeed #698. All the errors came from this type:
```cs
// Unity.ProBuilder, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
// UnityEngine.ProBuilder.Shapes.ProBuilderShape
```
They were from asset bundles and had type trees. The game version I checked was `1.0.19866`.

Duplicate of #698

**Comment by ds5678** [comment] 2023-10-26 10:56
Duplicate of https://github.com/AssetRipper/AssetRipper/issues/698

**Closed by ds5678** 2023-10-26 10:55 UTC
Labels: bug
