### ISSUE TITLE
[Bug]:  Error during reading of asset type

### ISSUE THREAD

**Issue by NomadWithoutAHome** [AssetRipper/AssetRipper#899] opened 2023-07-08 06:44 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/1123050/

### Which Unity version did this occur on?

2020.3.37

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Lots of Errors 
See Log 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11988757/AssetRipper.log)

**Comment by ds5678** [comment] 2023-07-08 12:56
Duplicate of #252

**Closed by ds5678** 2023-07-08 12:56 UTC
Labels: bug
