### ISSUE TITLE
[Bug]: Unable to read MonoBehavior scripts of type `Naninovel.Script`

### ISSUE THREAD

**Issue by nikitalita** [AssetRipper/AssetRipper#802] opened 2023-04-22 00:31 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Girls! Girls! Girls!?](https://steamdb.info/app/1412310/)

This occurs in the full game and the demo version

### Which Unity version did this occur on?

Demo - 2019.4.1f1
Full -  2021.3.16f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When attempting to load game scripts that contain dialogue, AssetRipper throws the following error:

Demo (2019.4.x)
```
Import : Unable to read MonoBehaviour Structure, because script Naninovel.Script layout mismatched binary content (ArgumentOutOfRangeException).
```
![image](https://user-images.githubusercontent.com/69168929/233752095-ebcc7cf4-aeca-4c10-9e85-9b6712a1f1fa.png)

Full Game (2021.3.x)
The Full game has a similar error message but with a different stated reason:

```
Import [Error] : Unable to read MonoBehaviour Structure, because script Naninovel.Script layout mismatched binary content (read 540 bytes, expected 33208 bytes).
```
![image](https://user-images.githubusercontent.com/69168929/233751877-342fd21f-a8c2-44e4-b04a-3161964e4831.png)

These scripts are located under resource.assets -> MonoBehavior. Earliest ones that are of this type are 001 and Demo001

### Relevant log output

[AssetRipper.log (Demo)](https://github.com/AssetRipper/AssetRipper/files/11299881/AssetRipper.log)
[AssetRipper.log (Full Game)](https://github.com/AssetRipper/AssetRipper/files/11299863/AssetRipper.log)

**Comment by ds5678** [comment] 2023-04-22 00:43
Duplicate of #698

**Closed by ds5678** 2023-04-22 00:43 UTC
Labels: bug

**Comment by SJCoding0130** [comment] 2024-08-29 17:49
same issue here
