### ISSUE TITLE
[Bug]: CMD error, not sure...

### ISSUE THREAD

**Issue by WanderCute** [AssetRipper/AssetRipper#748] opened 2023-02-25 07:20 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

assetripper latest version, vrchat avatar (.vrca)

### Which Unity version did this occur on?

2019.4.31f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

while exporting the assets from a .vrca file i obtained an error with assetripper

### Relevant log output

System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.0.6
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Sat Feb 25 07:11:27 UTC 2023
System : UTC Compile Time: Mon Feb  6 22:39:18 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: C:\Users\Emily\Downloads\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : Attempting to read files from C:\Users\Emily\Downloads\avatar-PC-Legendary-Selestia.vrca
Import : Game file 'avatar-PC-Legendary-Selestia.vrca' has been found
Import : Mixed game structure has been found at C:\Users\Emily\Downloads\avatar-PC-Legendary-Selestia.vrca
Import : Files use the 'Unknown' scripting backend.
Import : Dependency 'Library/unity default resources' wasn't found
Import : Dependency 'Resources/unity_builtin_extra' wasn't found
General : Finished reading files
General : Processing assemblies...
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Terrain Alpha Texture Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Editor Format Conversion
General : Finished processing assets
General : About to begin export to C:\Users\Emily\Downloads\New folder\avatar-PC-Legendary-Selestia.vrca
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\Users\Emily\Downloads\New folder\avatar-PC-Legendary-Selestia.vrca...
Export : Starting export
Export : Game files have these Unity versions: 2019.4.31f1
Export : Exporting to Unity version 2019.4.31f1
Export : Preparing for export...
Export : Preparation complete. Starting to export now...
ExportedFile : 'wing1_L.001' exported
ExportedFile : 'Doctor Strange' exported
ExportedFile : 'Mega Rotate 2' exported
ExportedFile : 'RockExplosion' exported
ExportedFile : 'SELESTIA_halo' exported
ExportedFile : 'ZM_Locomotion' exported
ExportedFile : '??Gear_1' exported
ExportedFile : 'FoxHatController' exported
ExportedFile : 'Space Laser V2' exported
ExportedFile : 'ResetWorldConstraint' exported
ExportedFile : 'AFK 1' exported
ExportedFile : 'God of Kawaii (2)' exported
ExportedFile : 'Sphere Shader 11' exported
ExportedFile : 'S_Gear7' exported
ExportedFile : 'Inv_Ctrl_Enable' exported
ExportedFile : 'Venus 1' exported
ExportedFile : 'wing1_R.001' exported
ExportedFile : 'God of Kawaii' exported
ExportedFile : 'Mega Rotate' exported
ExportedFile : 'Super Rotate 2' exported
ExportedFile : 'Epic Sax Guy [Original] [HD]' exported
ExportedFile : 'ForceAnim' exported
ExportedFile : 'S_Gear3' exported
ExportedFile : 'Ultimate Gothic Ring Ex (Animation)' exported
ExportedFile : 'Dia' exported
ExportedFile : 'S_Gear5' exported
ExportedFile : 'Earth' exported
ExportedFile : 'Sun' exported
ExportedFile : 'Yuu Sama Logo Final' exported
ExportedFile : '??1' exported
ExportedFile : 'wing1_L.002' exported
ExportedFile : 'Super Rotate' exported
ExportedFile : 'Inv_Ctrl_Disable' exported
ExportedFile : '??2' exported
ExportedFile : 'td' exported
ExportedFile : 'SELESTIA_FX' exported
ExportedFile : 'S_Gear10' exported
ExportedFile : '??2??' exported
ExportedFile : 'Gothic ring 2' exported
ExportedFile : 'Brain Power' exported
ExportedFile : 'BLACK_DRAGON_LOGO' exported
ExportedFile : '??Gear_2' exported
ExportedFile : 'DestroyKaichi' exported
ExportedFile : 'S_Gear8' exported
ExportedFile : 'BadBoy' exported
ExportedFile : 'SELESTIA_Gesture' exported
ExportedFile : 'GameObject dance' exported
ExportedFile : '?????????' exported
ExportedFile : 'EXPLORATION SPACE' exported
ExportedFile : 'S_Gear4' exported
ExportedFile : 'Mercury' exported
ExportedFile : 'wing1_R.002' exported
ExportedFile : 'RockStaticGravity' exported
ExportedFile : 'Gothic ring 1' exported
ExportedFile : 'jetzt aber (1) 1_0' exported
ExportedFile : 'ayo rainbow' exported
ExportedFile : 'Hover_Action' exported
ExportedFile : 'lots of rings Ex [Animated]' exported
ExportedFile : 'S_Gear9' exported
ExportedFile : 'S_Gear6' exported
ExportedFile : 'S_Gear1' exported
ExportedFile : 'S_Gear2' exported
ExportedFile : 'Animator' exported
ExportedFile : 'Mars' exported
Export : Exporting scripts...
ExportedFile : 'ScriptExportCollection' exported
ExportedFile : 'prefab-id-v1_avtr_524ce0f9-8b1e-4488-9110-16104df2fed3_7426290212' exported
ExportedFile : 'Cheek' exported
ExportedFile : 'wp2567199' exported
ExportedFile : 'IdleVr' exported
ExportedFile : 'basicglow' exported
ExportedFile : 'MatCap2(HQ)' exported
ExportedFile : '3DnoiseTex128' exported
ExportedFile : 'tex_vfx-ult_particle_sprite_point-blurred-large' exported
ExportedFile : 'mat_vfx-ult_particle_sprite_raySide-add-[1.0]' exported
ExportedFile : 'BrainPowerON' exported
ExportedFile : 'T_Matcap_MC (20)' exported
ExportedFile : 'tex_vfx-ult_particle_sprite_softRing' exported
ExportedFile : 'Flare4cg' exported
ExportedFile : 'unnamed 1' exported
ExportedFile : 'T_Default_CM_1' exported
ExportedFile : '#0018_1' exported
ExportedFile : 'mat_vfx-ult_particle_spritesheet_plasma-alpha-[3.0] 1' exported
ExportedFile : 'poiyomiNewDefaultShadow' exported
ExportedFile : 'Body' exported
ExportedFile : 'tex_vfx-ult_particle_spritesheet_electric14' exported
ExportedFile : 'Default-Particle' exported
ExportedFile : 't_Ani_Wings_Kri_Wings_Emission' exported
ExportedFile : 'RGB ELEC KS' exported
ExportedFile : 'Gem' exported
ExportedFile : 'mat_vfx-ult_particle_sprite_point-blurred-large-alpha-[0.25]' exported
ExportedFile : 'tex_vfx-ult_particle_sprite_snow' exported
ExportedFile : 'Rock_frag_073' exported
ExportedFile : 'T_Fabric_N' exported
ExportedFile : 'G_Ring_1.007' exported
ExportedFile : '??Gear????2' exported
ExportedFile : 'MatcapNebula' exported
ExportedFile : 'Particles 1' exported
ExportedFile : 'Beam' exported
ExportedFile : 'Smoke_Sprite_10' exported
ExportedFile : 'combined_image_0_White_Cloth' exported
ExportedFile : 'Mesh1' exported
ExportedFile : 'Clothes Demon 1' exported
ExportedFile : 'Model_frag_003' exported
ExportedFile : 'tex_vfx-ult_particle_spritesheet_smoke2' exported
ExportedFile : 'Torus_0' exported
ExportedFile : 'ANEMONE_Piercing' exported
ExportedFile : 'mat_vfx-ult_particle_sprite_cloudlet-add-[1.0]' exported
ExportedFile : '1966-bump' exported
ExportedFile : 'FlameCore2' exported
ExportedFile : 'Over Render Test 1' exported
ExportedFile : 'Gold 1' exported
ExportedFile : 'T_Default_SR_1' exported
ExportedFile : 'Model_frag_037' exported
ExportedFile : 'Mesh1' exported
ExportedFile : 'T_Default_CM' exported
ExportedFile : 'Engine 2019.4.31f1' exported
ExportedFile : 'Grass1' exported
ExportedFile : 'Rock_frag_033' exported
ExportedFile : 'Hidden/.poiyomi/ Poiyomi Toon /KAICHI 7 - copia-KAICHI 7 - copia' exported
ExportedFile : 'tex_vfx-ult_particle_sprite_kh_twinkle-blurred' exported
ExportedFile : 'StarsSwirl' exported
ExportedFile : 'New Material' exported
ExportedFile : 'Gear7' exported
ExportedFile : 'T_Default_SR_1' exported
ExportedFile : 'proxy_fall_long' exported
ExportedFile : '2' exported
ExportedFile : 'Mesh5' exported
ExportedFile : 'default' exported
ExportedFile : 'mat_vfx-ult_particle_spritesheet_smoke-alpha-[3.0]' exported
ExportedFile : 'Generators' exported
ExportedFile : 'sharp_blue' exported
ExportedFile : 'Hidden/.poiyomi/ Poiyomi Toon /Selestia_hair-Selestia_hair' exported
ExportedFile : 'ZXXXX' exported
ExportedFile : 'Doppels shaders/Raymarching/Fractal Pyramid' exported
ExportedFile : 'Rock_frag_046' exported
ExportedFile : 'Underwear' exported
ExportedFile : 'dissolve' exported
System.Exception: Unable to decompress crunched texture
   at AssetRipper.Export.UnityProjects.Textures.CrunchHandler.DecompressCrunchWithUtinyDecoder(TextureFormat textureFormat, Int32 width, Int32 height, UnityVersion unityVersion, ReadOnlySpan`1 data) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\CrunchHandler.cs:line 60
   at AssetRipper.Export.UnityProjects.Textures.CrunchHandler.DecompressCrunch(TextureFormat textureFormat, Int32 width, Int32 height, UnityVersion unityVersion, ReadOnlySpan`1 data) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\CrunchHandler.cs:line 14
   at AssetRipper.Export.UnityProjects.Textures.TextureConverter.ConvertToBitmap(TextureFormat textureFormat, Int32 width, Int32 height, Int32 depth, Int32 imageSize, UnityVersion version, Byte[] data) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureConverter.cs:line 126
   at AssetRipper.Export.UnityProjects.Textures.TextureConverter.ConvertToBitmap(ITexture2D texture) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureConverter.cs:line 79
   at AssetRipper.Export.UnityProjects.Textures.TextureAssetExporter.Export(IExportContainer container, IUnityObjectBase asset, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureAssetExporter.cs:line 44
   at AssetRipper.Export.UnityProjects.Textures.TextureExportCollection.ExportInner(IExportContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Textures\TextureExportCollection.cs:line 63
   at AssetRipper.Export.UnityProjects.Project.Collections.AssetExportCollection.Export(IExportContainer container, String projectDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\Collections\AssetExportCollection.cs:line 24
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 271
   at AssetRipper.Export.UnityProjects.Project.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Project\ProjectExporter.cs:line 177
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 174
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 155
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 49

**Comment by WanderCute** [comment] 2023-02-25 07:26
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10830505/AssetRipper.log)
theres my log file for refrence.

**Comment by ds5678** [comment] 2023-02-25 07:56
Duplicate of #735

**Closed by ds5678** 2023-02-25 07:56 UTC
Labels: bug
