### ISSUE TITLE
[Bug]: Do a memory profile on ULTRAKILL

### ISSUE THREAD

**Issue by RandomGamingDev** [AssetRipper/AssetRipper#1422] opened 2024-07-21 05:00 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Linux x64

### Which game did this occur on?

Ultrakill
https://store.steampowered.com/app/1229490/ULTRAKILL/

### Which Unity version did this occur on?

2019.4.40 according to their latest update here: https://x.com/HakitaDev/status/1705278342386032826

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Here are the steps:
1. Open AssetRipper
2. Try to open `ULTRAKILL_Data` with AssetRipper
3. Asset extraction looks like it's going normally, but it's slowly using up all of your system RAM (tested it up to 12 GB+ of free RAM)
4. The program lags your computer for a moment and then itself crashes after when getting killed by the system due to taking up too much memory (More specifically it ends when finding assemblies during Mono initialization which in Ultrakill's case is this line: `Import : During Mono initialization, found 121 assemblies`)

This issue's likely related to this other issue regarding drastically increased memory usage in the newer versions #1409

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16323127/AssetRipper.log)

**Comment by ds5678** [comment] 2024-07-21 05:15
As a general rule of thumb for RAM, you can expect to need 3 times the game file size.

**Comment by ds5678** [comment] 2024-07-21 05:16
Closing as a duplicate of #1409

**Comment by RandomGamingDev** [comment] 2024-07-21 05:18
> As a general rule of thumb for RAM, you can expect to need 3 times the game file size.

Ultrakill's 1.9 GBs
I used 12 GB+, but actually closer to 13 GB which means I had 7 times the game file size in RAM which is far more than the 3 times you recommended

**Comment by RandomGamingDev** [comment] 2024-07-21 05:22
Also, if you need 3x the game file size how are you supposed to download the assets from games that are 75 GB+?
Not many people have 225 GB+ RAM

**Comment by ds5678** [comment] 2024-07-21 05:29
Also, what if you need 3x the game file size how are you supposed to download the assets from games that are 75 GB+?
Not many people have 225 GB+ RAM

People supposedly use a pagefile in this situation.

**Comment by RandomGamingDev** [comment] 2024-07-21 06:36
> > Also, what if you need 3x the game file size how are you supposed to download the assets from games that are 75 GB+?
> > Not many people have 225 GB+ RAM
> 
> People supposedly use a pagefile in this situation.

Are there really no alternatives in this case? Many if not most applications like these only store a small part on RAM and store the rest on disk automatically without requiring setting up a pagefile.

**Comment by ds5678** [comment] 2024-07-21 06:49
You are welcome to do your own investigations, but it's more-or-less required for AssetRipper to do various things. The processing stage is particularly unfriendly to dynamic loading. There may be areas for memory usage improvement in the import stage.

**Comment by RandomGamingDev** [comment] 2024-07-22 02:48
> You are welcome to do your own investigations, but it's more-or-less required for AssetRipper to do various things. The processing stage is particularly unfriendly to dynamic loading. There may be areas for memory usage improvement in the import stage.

I just tried using [AssetStudio](https://github.com/zhangjiequan/AssetStudio) on Ultrakill and it did so fine with even less memory. Is there something that only AssetRipper's doing that requires the extra memory?

**Comment by ds5678** [comment] 2024-07-22 02:52
AssetStudio is incomparable to AssetRipper.
* It handles a small subset of asset types and discards the rest.
* It does no processing on those assets, which is critical for high export of Unity projects.

**Closed** 2024-08-04 21:32 UTC
Labels: bug, performance

**Comment by ds5678** [comment] 2024-08-04 21:38
See #1409 for information about the results of that commit.
