### ISSUE TITLE
[Bug]: Playable-related assets missing

### ISSUE THREAD

**Issue by 2394425147** [AssetRipper/AssetRipper#336] opened 2022-03-27 01:15 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2018.4.7f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After decompiling a game, Unity doesn't recognize playable assets (showing up as missing scripts), and playable directors in the scenes (and prefabs) are missing (components not added).

I've also upgraded the project to 2021.2.17f1 but the issue doesn't seem fixed either...

Procedure:
 - Decompile a project using playable assets and playable directors with default settings + level 4 script content level, export all
 - Open with Unity 2018.4.7f1
 - Observe

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8356619/AssetRipper.log)

**Comment by ds5678** [comment] 2022-03-27 04:19
Not a bug; just an enhancement. Duplicate of #164

**Closed by ds5678** 2022-03-27 04:19 UTC
Labels: enhancement
