### ISSUE TITLE
Could not read stripped versions

### ISSUE THREAD

**Issue by Maxandkon** [AssetRipper/AssetRipper#1054] opened 2023-09-29 20:21 UTC
### Describe the issue

Greetings, if I may please ask, I cannot export the assets as they are all ".unreadable" for application
Is there any way to fix this? Perhaps if I provide some information/files in a report, or are such problems more wide-spread? 

I should note that I can see and get some assets past UABEA, but it does not get the materials and derivation of the models, so it is not too effective for me

Thank you for your time and for your possible answer!

**Comment by ds5678** [comment] 2023-09-29 20:35
Your title and content don't match.

**Comment by Maxandkon** [comment] 2023-09-29 20:58
Is there any way to resolve this? Perhaps by manually adjusting something, or is there no way?

I note there are 2 folders here, in one of them everything works fine (but it has almost no assets), in the other all the files give this error. And where everything works, it says that the unit version is 2022.1.16, while where it "unread" the unit version is 0.0.0a0

I apologize if I'm bothering you with insignificant issues, just really don't see/understand how to solve it

**Comment by ds5678** [comment] 2023-09-29 21:43
I don't even know what you're asking.

**Comment by ds5678** [comment] 2023-09-29 21:45
The Electron UI has the feature you need.

**Comment by ds5678** [comment] 2023-09-29 21:47
Duplicate of #252

**Closed** 2023-09-29 21:47 UTC
