### ISSUE TITLE
[Bug]: GLB Exporting Vertex Color Incorrectly

### ISSUE THREAD

**Issue by Minileandro** [AssetRipper/AssetRipper#887] opened 2023-07-03 14:48 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Club Penguin Island

### Which Unity version did this occur on?

2017.4.12f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

When exporting the game in glb, i noticed that AR did the vertex color much more bright than should be, and i used asset studio to compare both, and this problem after can affect much for example when is about lightmap part (Asset Studio looks right).
Here it is some examples:
![image](https://github.com/AssetRipper/AssetRipper/assets/53369145/db477ad7-c508-49dd-bc36-66014f294585)
![image (1)](https://github.com/AssetRipper/AssetRipper/assets/53369145/0358a263-fda5-47b1-bb05-67d35ab48b7e)

In game:
![image (2)](https://github.com/AssetRipper/AssetRipper/assets/53369145/2d6b61a2-5436-4b47-ac7e-e0c0e167356d)

**Comment by Minileandro** [comment] 2023-07-03 18:34
AS version compared to AR we can see get the lightmap with a more correct color (let's just ignore the errors in the lightmap, probably AS broke the uv's because this was extracted years ago lol)
![image](https://github.com/AssetRipper/AssetRipper/assets/53369145/92bfad32-d35b-4097-8aee-646b875ecb08)

In game:
![image (1)](https://github.com/AssetRipper/AssetRipper/assets/53369145/1215da14-852c-45ba-87c6-17c0bc864de7)

**Comment by Minileandro** [comment] 2023-07-04 23:50
You think this is some problem about Asset Ripper or can be other thing?

**Comment by ds5678** [comment] 2023-07-05 01:37
I'm unsure what the issue is.

Did you have static mesh separation enabled for this rip?

**Comment by Minileandro** [comment] 2023-07-05 09:23
No, because when I export in glb it already makes the meshes separately and correctly.
The problem is apparently in the way it generates the vertex colors of the meshes, which seem bright than they should be (so why resulted in a bright lightmap in some parts).

Here is more examples of vertex color (without any texture).

Asset Ripper:
![image](https://github.com/AssetRipper/AssetRipper/assets/53369145/107a9dbd-e97c-415e-a928-2426e77a242a)

Asset Studio:
![image](https://github.com/AssetRipper/AssetRipper/assets/53369145/73439672-9fbc-414a-80a5-758da10a61eb)

**Comment by ds5678** [comment] 2023-10-08 16:18
I think this was fixed in bff290910c1e0cc248c3c47cc8aa10eed59302cb.

**Closed by ds5678** 2023-10-08 16:18 UTC
Labels: bug, export, mesh
