### ISSUE TITLE
[Bug]: Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Texture2D/EXRFlags

### ISSUE THREAD

**Issue by PolarsBear** [AssetRipper/AssetRipper#274] opened 2022-02-21 13:05 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.31f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

It extracted everything just fine, but when it tried exporting the scripts, it immediately stopped, with this error. I've tried running it as administrator, changing the "C# Language Version" to "Automatic - Experimental", and using the newest version I could find, even using an older version didn't work...

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8109284/AssetRipper.log)
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19044.0
System : Operating System: Windows x64
System : AssetRipper Version: 0.1.9.3
System : AssetRipper Build Type: Release x64 Published
System : UTC Current Time: 21/02/2022 12:37:12
System : UTC Compile Time: Mon Feb 21 05:41:20 UTC 2022
VersionManager : Loading version handlers...
VersionManager : Finished loading version handlers.
Plugin : Loading plugins...
Plugin : Finished loading plugins.
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : IgnoreStreamingAssets: False
General : ExportPath: C:\AssetRipperGUI_win64\Ripped
General : ExportDependencies: False
General : IgnoreAssetBundleContentPaths: False
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshCoordinateSpace: Unity
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoExperimental
General : SpriteExportMode: Native
General : TerrainExportMode: Native
General : TextExportMode: Parse
General : Attempting to read files from C:\Program Files (x86)\Steam\steamapps\common\Valheim
Import : PC game structure has been found at 'C:\Program Files (x86)\Steam\steamapps\common\Valheim'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Game file 'level4' has been found
Import : Game file 'level5' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 49 assemblies
Import : Resource file 'sharedassets1.assets.resS' has been loaded
General : Finished reading files
General : About to begin export to C:\AssetRipperGUI_win64\Rip\valheim
General : Removing any files from a previous export...
Export : Attempting to export assets to C:\AssetRipperGUI_win64\Rip\valheim...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2019.4.31f1
Export : Exporting to Unity version 2019.4.31f1
Export : Preparing for export...
Import [Warning] : Assembly 'UnityEngine.Purchasing' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Advertisements' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.Stores' hasn't been found
Import [Warning] : Assembly 'com.unity.multiplayer-hlapi.Runtime' hasn't been found
Import [Warning] : Assembly 'Unity.Timeline' hasn't been found
Import [Warning] : Assembly 'UnityEngine.TestRunner' hasn't been found
Import [Warning] : Assembly 'Unity.TextMeshPro' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Monetization' hasn't been found
Import [Warning] : Assembly 'Purchasing.Common' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.Codeless' hasn't been found
Import [Warning] : Assembly 'UnityEngine.XR.LegacyInputHelpers' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.SecurityStub' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.SecurityCore' hasn't been found
Import [Warning] : Assembly 'UnityEngine.SpatialTracking' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.WinRTCore' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.AppleStub' hasn't been found
Import [Warning] : Assembly 'Unity.Analytics.DataPrivacy' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.AppleCore' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.AppleMacosStub' hasn't been found
Import [Warning] : Assembly 'UnityEngine.Purchasing.WinRTStub' hasn't been found
Import [Warning] : Assembly 'UnityEngine.TextCoreModule' hasn't been found
Import : Resource file 'sharedassets1.resource' has been loaded
Import : Resource file 'sharedassets3.resource' has been loaded
Export : Preparation complete. Starting to export now...
ExportedFile : 'UnknownObject_PlayerSettings' exported
ExportedFile : 'AssetRipper.Core.Classes.InputManager.InputManager' exported
ExportedFile : 'AssetRipper.Core.Classes.TagManager.TagManager' exported
ExportedFile : 'AssetRipper.Core.Classes.AudioManager.AudioManager' exported
ExportedFile : 'UnknownObject_ScriptMapper' exported
ExportedFile : 'AssetRipper.Core.Classes.GraphicsSettings.GraphicsSettings' exported
ExportedFile : 'AssetRipper.Core.Classes.TimeManager' exported
ExportedFile : 'UnknownObject_DelayedCallManager' exported
ExportedFile : 'AssetRipper.Core.Classes.PhysicsManager.PhysicsManager' exported
ExportedFile : 'AssetRipper.Core.Classes.BuildSettings' exported
ExportedFile : 'AssetRipper.Core.Classes.QualitySettings.QualitySettings' exported
ExportedFile : 'AssetRipper.Core.Classes.NavMeshProjectSettings.NavMeshProjectSettings' exported
ExportedFile : 'AssetRipper.Core.Classes.Physics2DSettings.Physics2DSettings' exported
ExportedFile : 'UnknownObject_RuntimeInitializeOnLoadManager' exported
ExportedFile : 'UnknownObject_StreamingManager' exported
ExportedFile : 'UnknownObject_VFXManager' exported
Import : Resource file 'level0.resS' has been loaded
ExportedFile : 'Cubemap' exported
ExportedFile : 'UnknownObject_LightProbes' exported
ExportedFile : 'level0' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'Mesh' exported
ExportedFile : 'level1' exported
ExportedFile : 'UnknownObject_AudioLowPassFilter' exported
ExportedFile : 'level2' exported
ExportedFile : 'level3' exported
Import : Resource file 'level4.resS' has been loaded
ExportedFile : 'Cubemap' exported
ExportedFile : 'UnknownObject_LightProbes' exported
ExportedFile : 'level4' exported
Import : Resource file 'level5.resS' has been loaded
ExportedFile : 'Cubemap' exported
ExportedFile : 'level5' exported
Export : Exporting scripts...
[Error] : Mono.Cecil.ResolutionException: Failed to resolve UnityEngine.Texture2D/EXRFlags
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream)
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver.CreatePEFile(AssemblyDefinition assembly) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 42
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(ReadOnlySpan`1 assemblies) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 20
   at AssetRipper.Library.Exporters.Scripts.CecilAssemblyResolver..ctor(IAssemblyManager manager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\CecilAssemblyResolver.cs:line 15
   at AssetRipper.Library.Exporters.Scripts.ScriptDecompiler..ctor(IAssemblyManager assemblyManager) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptDecompiler.cs:line 18
   at AssetRipper.Library.Exporters.Scripts.ScriptExporter.Export(IExportContainer container, IEnumerable`1 assets, String dirPath, Action`3 callback) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExporter.cs:line 91
   at AssetRipper.Library.Exporters.Scripts.ScriptExportCollection.Export(ProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\Scripts\ScriptExportCollection.cs:line 80
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 157
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 68
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 90
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 151
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 132
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55

**Comment by ds5678** [comment] 2022-02-25 07:32
This is happening because Mono.Cecil is failing to save assemblies. You can work around this by setting the Script Content Level to 0.

**Comment by ds5678** [comment] 2022-02-25 20:52
Closing as a duplicate of #227

**Closed by ds5678** 2022-02-25 20:52 UTC
Labels: bug
