### ISSUE TITLE
[Bug]: Unity Editor crashes on import

### ISSUE THREAD

**Issue by MadMincraftr** [AssetRipper/AssetRipper#878] opened 2023-06-28 18:52 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Slime Rancher 1 https://steamdb.info/app/433340/info/

### Which Unity version did this occur on?

2019.4.29f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Some files have the `0000000000000000f000000000000000` guid, which crashes unity editor.
There is no error in the AssetRipper log, it just said exported.
One thing i noticed, is when it tried to read `0000000000000000` as a area in memory, that is the exact amount of zeros that are in the first part of the bugged guid.

### Relevant log output

Instead of the asset ripper log, which has no errors, i will give you the Unity Log
```Unity Editor by Unity Technologies [version: Unity 2019.4.29f1_0eeae20b1d82]

Unity.exe caused an Access Violation (0xc0000005)
  in module Unity.exe at 0033:81c971bd.

Error occurred at 2023-06-28_134958.
C:\Program Files\Unity\Hub\Editor\2019.4.29f1\Editor\Unity.exe, run by Thean Mcgarity.

52% physical memory in use.
32681 MB physical memory [15367 MB free].
673 MB process peak paging file [483 MB used].
605 MB process peak working set [408 MB used].
System Commit Total/Limit/Peak: 30619MB/51859MB/44187MB
System Physical Total/Available: 32681MB/15367MB
System Process Count: 415
System Thread Count: 6909
System Handle Count: 365118
Disk space data for 'C:\Users\THEANM~1\AppData\Local\Temp\Unity\Editor\Crashes\Crash_2023-06-28_184956811\': 14953095168 bytes free of 498736295936 total.

Read from location 0000000000000000 caused an access violation.

Context:
RDI:    0x0000000000000000  RSI: 0x0000000000000000  RAX:   0x0000000000000000
RBX:    0x00000018b477ae60  RCX: 0x00000018b477ae87  RDX:   0x000001df8c554fa0
RIP:    0x00007ff681c971bd  RBP: 0x00000018b477ae50  SegCs: 0x000001df00000033
EFlags: 0x0000000000010246  RSP: 0x00000018b477ad10  SegSs: 0x000001df0000002b
R8:     0x0000000000000027  R9:  0x0000000000000027  R10:   0x000001f840ccfe00
R11:    0x00000018b477ae60  R12: 0x0000000000000000  R13:   0x00007ff683e1e470
R14:    0x000001f880301628  R15: 0x0000000000000000


Bytes at CS:EIP:
48 8b 07 48 8b d3 48 8b cf ff 50 70 90 48 8b c3 

Mono DLL loaded successfully at 'C:\Program Files\Unity\Hub\Editor\2019.4.29f1\Editor\Data\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.


Stack Trace of Crashed Thread 37332:
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF681C971BD)
0x00007FF681C971BD (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF68288F5E0)
0x00007FF68288F5E0 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF6804DDE7A)
0x00007FF6804DDE7A (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF6804DECE0)
0x00007FF6804DECE0 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF68046E825)
0x00007FF68046E825 (Unity) (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF68046F320)
0x00007FF68046F320 (Unity) (function-name not available)```

**Comment by ds5678** [comment] 2023-06-28 19:10
> One thing i noticed, is when it tried to read 0000000000000000 as a area in memory, that is the exact amount of zeros that are in the first part of the bugged guid.

The number of zeros is unrelated to that guid. 64 bit pointers use 16 digits when expressed as a hexadecimal. In this case, that number signifies the null pointer, which means that Unity is really stupid for throwing an error here.

If I had to guess, I'd say this is caused by #811

**Comment by ds5678** [comment] 2023-07-02 21:30
I'm going to close this as a duplicate of #811. If you discover that it is caused by something else, feel free to reopen the issue and provide more details.

**Closed by ds5678** 2023-07-02 21:30 UTC
Labels: bug
