### ISSUE TITLE
[Bug]: unity version dectected as 0.0.0a0

### ISSUE THREAD

**Issue by KoleckOLP** [AssetRipper/AssetRipper#743] opened 2023-02-20 13:29 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Gorillaz Escape to Plastic Beach, abadonware iOS game, I can provide link if you ask me.
Don't wanna post it here to not get my bug report banned

### Which Unity version did this occur on?

AssetRipper 2.4.2 says it's unity 2.5.0a0
AssetRipper 3.0.6 says it's unity 0.0.0a0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I drag and drop the ipa file onto the latest version of AssetRipper and if I export it fails
![AssetRipper_S4oHMlmrhX](https://user-images.githubusercontent.com/22729896/220121467-e8170133-a11a-4af3-aaf3-7229c22784a9.png)
but in AssetRipper 2.4.2 it works fine, it exports and everything
![AssetRipper_ZH4mpIynuh](https://user-images.githubusercontent.com/22729896/220121519-13adaddb-0778-4daf-9c50-67fbbba33d76.png)

### Relevant log output

3.0.6
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10784823/AssetRipper.log)
2.4.2
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10784842/AssetRipper.log)

**Comment by KoleckOLP** [comment] 2023-02-20 14:07
I think the old version also guessed the Unity version wrong cause some files are called 3.0.0f5
is there any way to export this game correctly I just got a ton of files with .unreadable extencion

**Comment by KoleckOLP** [comment] 2023-02-20 14:20
Oh the problem is that tha game was made in a unity version that is not supported by AssetRipper
Any plan for supporting versions lower than 3.4.0?

**Comment by ds5678** [comment] 2023-02-21 04:13
> unity version dectected as 0.0.0a0

Duplicate of #252 

> Any plan for supporting versions lower than 3.4.0?

Future plans for AssetRipper likely involve going in the other direction. I'm considering dropping 3.4 support and having the lowest supported version be 3.5.0 because it would simplify a large amount of code.

**Closed by ds5678** 2023-02-21 04:13 UTC
Labels: bug
