### ISSUE TITLE
Mac File Dialog Needs to be on the Main Thread

### ISSUE THREAD

**Issue by kenzWeb** [AssetRipper/AssetRipper#1179] opened 2024-02-01 02:53 UTC
### Question

I get this error when I want to import a file:
<img width="1440" alt="Снимок экрана 2024-02-01 в 05 51 37" src="https://github.com/AssetRipper/AssetRipper/assets/77916046/17dfedad-1372-41f6-ad42-dfbe9bd3f5e0">

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by kenzWeb** [comment] 2024-02-01 02:54
> Thank you for submitting your first issue here. Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14119679/AssetRipper.log)

**Comment by ds5678** [comment] 2024-02-01 04:18
There is some discussion about this in #1154. If your Mac is Arm64, then this is a duplicate of that issue.

**Closed** 2024-02-04 16:28 UTC
