### ISSUE TITLE
[Bug]: Instant Crash when trying to export sprites as Texture

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#957] opened 2023-07-29 09:18 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Any games (tested on 4 different games)

### Which Unity version did this occur on?

tested on unity game version 2019, 2020, 2021,

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Hello ;)

I have a crash with no log at the beginning of the export process when I change the Sprite Export from YAML to Texture.
Crash occurs at the very beginning of the export process, when trying to read sharedassets
The log reports no errors(...) see attached log
I did howether manage to copy the error showed in the console (but not in the log) just before the app crashes and closes:
need to be very quick at copy/pasting ... ;) before app closes

Using the latest commit as of today.
This is the error I managed to copy from the console:

------------------------------------------------------------------------------------------------------------------
```
Process terminated. Assertion failed.
   at AssetRipper.Export.UnityProjects.Textures.TextureExportCollection..ctor(TextureAssetExporter assetExporter, SpriteInformationObject spriteInformationObject, Boolean exportSprites) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\Textures\TextureExportCollection.cs:line 32
   at AssetRipper.Export.UnityProjects.Textures.TextureAssetExporter.TryCreateCollection(IUnityObjectBase asset, TemporaryAssetCollection temporaryFile, IExportCollection& exportCollection) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\Textures\TextureAssetExporter.cs:line 28
   at AssetRipper.Export.UnityProjects.ProjectExporter.CreateCollection(TemporaryAssetCollection file, IUnityObjectBase asset) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 127
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, IEnumerable`1 files, CoreConfiguration options) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 220
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle fileCollection, CoreConfiguration options) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\ProjectExporter.cs:line 183
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Func`2 filter, Action`1 onBeforeExport) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 185
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(String exportPath, Action`1 onBeforeExport) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 164
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, MainWindowViewModel vm, String toRoot, Action onSuccess, Action`1 onError) in F:\_DEV2\AssetRipper-master\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 46
   at AssetRipper.GUI.Managers.UIExportManager.<>c__DisplayClass1_0.<Export>b__0() in F:\_DEV2\AssetRipper-master\Source\AssetRipper.GUI\Managers\UIExportManager.cs:line 24
```
------------------------------------------------------------------------------------------------------------------

I tried with different games, and result is always the same ;(
Sprite texture export is broken...

Hope you can fix it.
Kind regards
Z

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12206732/AssetRipper.log)

**Comment by ds5678** [comment] 2023-07-31 00:39
> System : AssetRipper Build Type: Debug Compiled

Debug mode doesn't catch exceptions. That's what the debugger is for. If you want to see stacktraces in the log, compile in release mode or download an alpha build.

**Comment by ds5678** [comment] 2023-07-31 00:42
In any case, I assume [this assertion](https://github.com/AssetRipper/AssetRipper/blob/3156d5e123528c7f61b0eb01c21ce7dcf3e2ad65/Source/AssetRipper.Export.UnityProjects/Textures/TextureExportCollection.cs#L32) is failing, which probably indicates a bug in sprite processing. That would make this a loose duplicate of #779.

**Comment by Zbuffers** [comment] 2023-07-31 07:28
Hi, 

WTF ?? ;)
When i compile in release mode and try the same export (only change sprite export from YAML to Texture), then it exports with no errors !!!

I will make sure to compile in Release mode from now on...

Kind regards,
Z

**Closed** 2023-07-31 10:28 UTC
Labels: bug
