### ISSUE TITLE
[Bug]: BrotliFile Load Failure

### ISSUE THREAD

**Issue by chillowdev** [AssetRipper/AssetRipper#673] opened 2023-01-03 19:21 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.axlebolt.standoff2

The latest version of the game is 0.22.0, but I tried to rip version 0.15.0
Old binaries can be found here https://trashbox.ru/link/standoff-2-android

### Which Unity version did this occur on?

Unity 2019.4.10 (from apk)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The game scripting backend is il2cpp, but I don't export scripts

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10339162/AssetRipper.log)

**Comment by ds5678** [comment] 2023-03-30 05:30
I could not reproduce your issue because I could not acquire `0.15.0`. I was able to acquire `0.22.3`, and it did not have this issue.

**Comment by ds5678** [comment] 2023-06-07 17:12
Duplicate of #850

**Closed by ds5678** 2023-06-07 17:12 UTC
Labels: bug, import
