### ISSUE TITLE
[Enhancement]: Support for Sub State Machines in Animator Controllers

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1018] opened 2023-09-03 17:00 UTC
### Describe the new feature or enhancement

Hi,

Support for sub state machines in Animator controllers would be great.
As an example here are 2 screenshots of the same animator controller:
using sub state machines (from some other app ...) that does a super bad job with animator parameters, btw, notice the additive and sync attributes are missing):
![SubStateMachines](https://github.com/AssetRipper/AssetRipper/assets/7527771/3c0e988c-f05e-4afb-8b23-c4c47991ae0f)
without sub state machines (ripper):
![Animator](https://github.com/AssetRipper/AssetRipper/assets/7527771/bc1d0b66-be20-4cd1-94fd-6bdb4dcbee48)

see the difference ? ;)

As always,
Keep up the super great work ;)
King regards,
Z

**Comment by ds5678** [comment] 2023-09-03 19:55
Duplicate of #679

**Closed** 2023-09-03 19:56 UTC
Labels: enhancement
