### ISSUE TITLE
[Bug]: MonoBehaviour component reset to default when component has a LocalizedString variable.

### ISSUE THREAD

**Issue by AALUND13** [AssetRipper/AssetRipper#1277] opened 2024-03-30 22:23 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Rounds (Steam)

### Which Unity version did this occur on?

2022.3.18f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

 Upon importing the "Rounds" folder, numerous "Unable to read MonoBehaviour Structure" errors were encountered, indicating a mismatch in binary content. Subsequently, attempting to export all files resulted in the persistence of these errors, particularly affecting components containing a LocalizedString variable. This led to the reset of default values within affected components, notably observed with the "CardInfo" script.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14813474/AssetRipper.log)

**Comment by ds5678** [comment] 2024-03-30 22:24
I assume LocalizedString uses `[SerializeReference]`?

**Comment by AALUND13** [comment] 2024-03-30 23:32
No, I use dnspy This what the class looked like 
![image](https://github.com/AssetRipper/AssetRipper/assets/58748165/89b82a55-10b5-4cfb-adfb-5779a0946388)

**Comment by ds5678** [comment] 2024-03-31 00:03
And you're sure that one of the base classes doesn't use it?

**Comment by AALUND13** [comment] 2024-04-05 23:01
I checked the LocalizedString and examined the CurrentLoadingOperationHandle property, which belongs to the LocalizedDatabase class. In the LocalizedDatabase class, some properties are marked with the SerializeReference attribute.

**Comment by ds5678** [comment] 2024-04-06 00:10
Duplicate of #698

**Closed** 2024-04-06 00:10 UTC
Labels: bug
