### ISSUE TITLE
[Bug]: I get an error when exporting

### ISSUE THREAD

**Issue by tuanvus** [AssetRipper/AssetRipper#579] opened 2022-10-18 16:54 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.dxx.firenow

### Which Unity version did this occur on?

2020.3.38

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

it got an error can't export
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9813072/AssetRipper.log)

**Comment by ds5678** [comment] 2022-10-31 15:20
Duplicate of #556

**Closed by ds5678** 2022-10-31 15:20 UTC
Labels: bug

**Comment by ds5678** [comment] 2022-12-01 03:43
Try https://github.com/AssetRipper/AssetRipper/actions/runs/3588783128 and let me know how it goes.
