### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zero16832** [AssetRipper/AssetRipper#390] opened 2022-05-13 01:29 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

System.NullReferenceException: Object reference not set to an instance of an object.
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.AddTransformCurve(Single time, TransformType transType, IReadOnlyList`1 curveValues, IReadOnlyList`1 inSlopeValues, IReadOnlyList`1 outSlopeValues, Int32 offset, String path) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 356
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.ProcessConstant(IClip clip, IAnimationClipBindingConstant bindings, IReadOnlyDictionary`2 tos, Single lastFrame) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 197
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 74
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipConverter.Process(IAnimationClip clip) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipConverter.cs:line 53
   at AssetRipper.Library.Exporters.AnimationClips.AnimationClipExportCollection.ExportInner(IProjectAssetContainer container, String filePath, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Exporters\AnimationClips\AnimationClipExportCollection.cs:line 22
   at AssetRipper.Core.Project.Collections.AssetExportCollection.Export(IProjectAssetContainer container, String dirPath) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\Collections\AssetExportCollection.cs:line 57
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 171
   at AssetRipper.Core.Project.ProjectExporterBase.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Project\ProjectExporterBase.cs:line 82
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 98
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 162
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 143
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIExportManager.cs:line 55

**Comment by zero16832** [comment] 2022-05-13 01:29
this game ripper in 1.9 is can't use. but not in 2.0

**Comment by ds5678** [comment] 2022-05-13 01:38
duplicate of #389 which was fixed a couple hours ago

**Closed by ds5678** 2022-05-13 01:38 UTC
Labels: bug
