### ISSUE TITLE
[Bug]: Fire Emblem Engage throws MULTIPLE errors

### ISSUE THREAD

**Issue by Demonslayerx8** [AssetRipper/AssetRipper#700] opened 2023-01-19 18:44 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Switch: Fire Emblem Engage

### Which Unity version did this occur on?

Some files have different versions, but only 2 has been seen
2020.3.14f1
2020.3.18f1

Opens fine in AssetStudio, but some data fails to load, and textures are swizzled. Exporting data as raw only spits out the header of the texture data, but sadly can't find the full texture data, thus can't export properly to manually convert and deswizzle (yay for ASTC textures?).

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Just fails to load assets. If needed, can provide some files.

### Relevant log output

log file
[AssetRipper.zip](https://github.com/AssetRipper/AssetRipper/files/10460066/AssetRipper.zip)

**Comment by ds5678** [comment] 2023-01-19 18:51
Duplicate of #252

**Closed by ds5678** 2023-01-19 18:51 UTC
Labels: bug
