### ISSUE TITLE
[Other]: Broken Textures upon ripping

### ISSUE THREAD

**Issue by amVspR** [AssetRipper/AssetRipper#768] opened 2023-03-21 10:00 UTC
### Describe the issue

Hi, I encounterd a problem where the textures were broken as shown in the attached photo. Please take a look at this problem. I'd much appreciate if it could be solved. Thank you.
I'm using the latest Asset Ripper. Windows 10, x64. Unity version of the game: I think it's 2021.3.11f1.
Here're some folders of the game (Excluding the large-sized "Assetbundles" & "Movie" ones): https://drive.google.com/drive/folders/1zbD4_xDqqmoxOY1r72d8990GgbsI5dhn?usp=share_link
**Also attached herewith the log file. If you further need any file from the game, I'll be happy to comply with.**
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11026916/AssetRipper.log)
![brokentextures](https://user-images.githubusercontent.com/95906567/226571964-0fc23038-81ba-4d0f-b5f6-7df17160c85b.jpg)

**Comment by ds5678** [comment] 2023-03-21 17:27
That is texture swizzling.

**Comment by ds5678** [comment] 2023-03-21 17:29
Duplicate of #629

**Closed** 2023-03-21 17:29 UTC
