### ISSUE TITLE
5.4.0b17 Type Trees

### ISSUE THREAD

**Issue by NonCodeMan** [AssetRipper/AssetRipper#1017] opened 2023-09-03 06:27 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

The first version of rec room https://steamdb.info/app/471710/

### Which Unity version did this occur on?

![Screenshot 2023-09-03 022631](https://github.com/AssetRipper/AssetRipper/assets/115851995/5f349537-39f7-43d6-8906-53002abb3ed9)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I actually don't know how to describe it all I know is that it happens on utinyRipper and now it's happening here

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12505285/AssetRipper.log)

**Comment by NonCodeMan** [comment] 2023-09-03 06:29
sorry im Tired and I didn't notice the question
"Is the game Mono or IL2Cpp?"
And to be honest I don't really know

**Comment by githubexplorer2342** [comment] 2023-09-03 13:27
@ds5678 Will 5.0 beta versions be dumped or are they considered lost? I have a game that uses unity 5.0.0b12

**Comment by Prosopho** [comment] 2023-09-03 13:35
> sorry im Tired and I didn't notice the question "Is the game Mono or IL2Cpp?" And to be honest I don't really know

It's il2cpp. I checked it.

**Comment by ds5678** [comment] 2023-09-03 13:36
If I remember correctly, all beta versions before Unity 5.4.0b22 require a Unity Pro subscription. I am unsure of the exact version boundary, and there may be a way to subvert the subscription requirement. However, the cost is high and the benefit is small, so I might never work on implementing support for dumping them.

**Comment by NonCodeMan** [comment] 2023-09-03 16:02
I tried on a newer version and it worked it's just having errors exporting
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12506522/AssetRipper.log)

**Comment by ds5678** [comment] 2023-09-19 14:41
I'm closing this as a duplicate of https://github.com/AssetRipper/TypeTreeDumps/issues/25

**Closed by ds5678** 2023-09-19 14:41 UTC
Labels: bug, import
