### ISSUE TITLE
[Bug]: Extraction is not parallel on Linux

### ISSUE THREAD

**Issue by hykilpikonna** [AssetRipper/AssetRipper#1221] opened 2024-02-28 01:09 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Linux x64

### Which Unity version did this occur on?

5.6.4f

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

From what I've heard in the discord, running this on Windows might be parallel. However, when extracting a directory of asset bundle files on Linux, this program is only able to utilize one CPU core when opening and extracting the directory, even though it has ~80 threads.

![image](https://github.com/AssetRipper/AssetRipper/assets/22280294/09501e6b-f503-4f96-a428-664a633267d0)

### Relevant log output

This log contains sensitive information so I will only include the relevant lines:

```log
> head AssetRipper.log                                       
System : AssetRipper
System : System Version: Unix 6.7.6.1
System : Operating System: Linux x64
System : AssetRipper Version: 1.0.8.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Wed Feb 28 00:54:57 UTC 2024
System : UTC Compile Time: Mon Feb 26 06:21:04 UTC 2024
```

**Comment by ds5678** [comment] 2024-02-28 01:35
Duplicate of #699

**Closed by ds5678** 2024-02-28 01:35 UTC
Labels: bug
