### ISSUE TITLE
[Bug]: The program crashes when unpacking the game.

### ISSUE THREAD

**Issue by MARK2580** [AssetRipper/AssetRipper#872] opened 2023-06-24 16:34 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/641320/

### Which Unity version did this occur on?

2018.4.2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I tried to fully unpack the Cooking Simulator game. At about 10% of unpacking, an error message appears and when you click OK, the program closes.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11857665/AssetRipper.log)

**Comment by ds5678** [comment] 2023-06-25 21:02
Duplicate of #871

**Closed by ds5678** 2023-06-25 21:02 UTC
Labels: bug
