### ISSUE TITLE
[Bug]: System.ArgumentException when exporting Pokemon Brilliant Diamond files

### ISSUE THREAD

**Issue by realmadrid1809** [AssetRipper/AssetRipper#1410] opened 2024-07-10 14:38 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Pokemon Brilliant diamond

### Which Unity version did this occur on?

2019.4.27f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Unable to export the game files from this game when using the Unity texture format.
This used to be possible on version 1.04.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16163628/AssetRipper.log)

**Comment by ds5678** [comment] 2024-08-11 18:05
Duplicate of #1368

**Closed by ds5678** 2024-08-11 18:05 UTC
Labels: bug, textures
