### ISSUE TITLE
[Bug]: the combined size of all the meshes exceeds the maximum capacity of the buffers

### ISSUE THREAD

**Issue by land1and** [AssetRipper/AssetRipper#1600] opened 2024-12-16 09:51 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/252490/

### Which Unity version did this occur on?

2022.3.41f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

exception happened about 3 hours into exporting the bundles folder using "Export Primary Content"

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/18147960/AssetRipper.log)

**Comment by ds5678** [comment] 2024-12-16 14:29
Duplicate of #1557

**Closed** 2024-12-16 14:29 UTC
Labels: bug
