### ISSUE TITLE
[Bug]:  Mixed game structure has been found at

### ISSUE THREAD

**Issue by theolovesyou** [AssetRipper/AssetRipper#310] opened 2022-03-14 18:00 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

engine version : Unity 5.0.4f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Mixed game structure has been found at
[sharedassets68.zip](https://github.com/AssetRipper/AssetRipper/files/8247433/sharedassets68.zip)

### Relevant log output

System.OverflowException: Arithmetic operation resulted in an overflow.
   at AssetRipper.Core.Parser.Files.SerializedFiles.Parser.SerializedTypeBase.set_OriginalTypeID(Int32 value) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\Parser\SerializedTypeBase.cs:line 85
   at AssetRipper.Core.Parser.Files.SerializedFiles.Parser.SerializedTypeBase.Read(SerializedReader reader, Boolean hasTypeTree) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\Parser\SerializedTypeBase.cs:line 29
   at AssetRipper.Core.Parser.Files.SerializedFiles.Parser.SerializedType.Read(SerializedReader reader, Boolean hasTypeTree) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\Parser\SerializedType.cs:line 17
   at AssetRipper.Core.Parser.Files.SerializedFiles.IO.SerializedReader.ReadSerializedTypeArray[T](Boolean hasTypeTree) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\IO\SerializedReader.cs:line 42
   at AssetRipper.Core.Parser.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(SerializedReader reader) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\Parser\SerializedFileMetadata.cs:line 94
   at AssetRipper.Core.Parser.Files.SerializedFiles.Parser.SerializedFileMetadata.Read(Stream stream, SerializedFileHeader header) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\Parser\SerializedFileMetadata.cs:line 57
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFileScheme.ReadScheme() in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFileScheme.cs:line 79
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFileScheme.ReadSceme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFileScheme.cs:line 48
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Parser\Files\SerializedFile\SerializedFile.cs:line 81
   at AssetRipper.Core.Structure.SchemeReader.ReadScheme(SmartStream stream, String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 69
   at AssetRipper.Core.Structure.SchemeReader.LoadScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\SchemeReader.cs:line 19
   at AssetRipper.Core.Structure.GameStructure.GameStructureProcessor.AddScheme(String filePath, String fileName) in D:\a\AssetRipper\AssetRipper\AssetRipperCommon\Structure\GameStructure\GameStructureProcessor.cs:line 29
   at AssetRipper.Core.Structure.GameStructure.GameStructure.ProcessPlatformStructure(GameStructureProcessor processor, PlatformGameStructure structure) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 125
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 60
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 40
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipperCore\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipperLibrary\Ripper.cs:line 116
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipperGUI\Managers\UIImportManager.cs:line 24

**Comment by ds5678** [comment] 2022-03-14 18:01
Duplicate of #296 which is being worked on

**Closed by ds5678** 2022-03-14 18:01 UTC
Labels: bug
