### ISSUE TITLE
[Bug]: Item with the same key exists

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#568] opened 2022-10-05 03:47 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

And older version of Cross Road

### Which Unity version did this occur on?

Unknown

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Open the folder, pop up with error and see logs.

This is the log entry

Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
[Error] : System.ArgumentException: An item with the same key has already been added. Key: level1
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformGameStructure.CollectSerializedGameFiles(DirectoryInfo root, IDictionary`2 files) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformGameStructure.cs:line 173
   at AssetRipper.Core.Structure.GameStructure.Platforms.PlatformGameStructure.CollectFiles(Boolean skipStreamingAssets) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\PlatformGameStructure.cs:line 139
   at AssetRipper.Core.Structure.GameStructure.Platforms.AndroidGameStructure.CollectFiles(Boolean skipStreamingAssets) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Structure\GameStructure\Platforms\AndroidGameStructure.cs:line 75
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(List`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 51
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration, LayoutInfo layinfo) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 42
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 32
   at AssetRipper.Library.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 139
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIImportManager.cs:line 22

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9712445/AssetRipper.log)

**Comment by ds5678** [comment] 2022-10-05 03:50
I'm fairly sure this is a duplicate of some other issue.

**Comment by ds5678** [comment] 2022-10-05 03:51
Probably #281

**Comment by ds5678** [comment] 2022-10-05 03:52
Wait, no. The duplicate key is `level1`. How do you have two of that file?

**Comment by cyberangel67** [comment] 2022-10-05 03:55
They are split files if that helps
<img width="552" alt="Screenshot 2022-10-05 145456" src="https://user-images.githubusercontent.com/1366816/193978076-20bda7d4-a2ce-4308-a899-b035af401aa1.png">

**Comment by ds5678** [comment] 2022-10-05 03:57
Delete either the two split files or the singleton. The singleton is just a merger of the other two.

**Comment by ds5678** [comment] 2022-10-05 03:58
Unless AssetRipper created the singleton (which I highly doubt), this is not its fault.

**Comment by cyberangel67** [comment] 2022-10-05 04:04
Are you saying the two splits are obsolete?

**Comment by ds5678** [comment] 2022-10-05 04:04
Yes

**Comment by ds5678** [comment] 2022-10-05 04:05
Notice how their sizes sum up to the original.

**Comment by cyberangel67** [comment] 2022-10-05 04:12
Ok that bypassed the error, what would it take to silently ignore that going forward?

**Comment by ds5678** [comment] 2022-10-05 04:17
Are you certain that merged file even came with the game? It seems probable that some other tool merged the split files.

**Comment by cyberangel67** [comment] 2022-10-05 04:22
Its from the original APK as far as I recall, I no longer have that APK so I will have to go find it. Generally in those days I manually extracted the APK's and then ripped the file using these tools to a completely different folder and drive

**Comment by ds5678** [comment] 2022-10-05 04:26
The work for #281 should make AssetRipper more forgiving in these kind of situations.

**Closed by ds5678** 2022-10-05 04:26 UTC
Labels: bug
