### ISSUE TITLE
[Bug]: Unable to read MonoBehaviour Structure, because script layout mismatched binary content

### ISSUE THREAD

**Issue by OlenaKudria** [AssetRipper/AssetRipper#1068] opened 2023-10-16 20:02 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Sand Story](https://steamdb.info/app/1749420/)

### Which Unity version did this occur on?

2021.1.11

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

The problem is with the Naninovel asset. `Unable to read MonoBehaviour Structure, because script Naninovel.***** layout mismatched binary content` It does not work with its .nani extension. 

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12921315/AssetRipper.log)

**Comment by ds5678** [comment] 2023-10-26 11:11
I was unable to acquire the game, but this is likely https://github.com/AssetRipper/AssetRipper/issues/698.

**Comment by OlenaKudria** [comment] 2023-10-29 20:11
> I was unable to acquire the game, but this is likely #698.

why u think so?

**Comment by ds5678** [comment] 2023-10-29 20:27
More likely to be one thing wrong than two.

**Comment by ds5678** [comment] 2023-11-07 04:07
I'm closing this because I can't test and because it's likely a duplicate of the other issue. Feel free to reopen if either of these reasons becomes no longer valid.

**Closed by ds5678** 2023-11-07 04:07 UTC
Labels: bug
