### ISSUE TITLE
[Bug]: Issue Ripping APK

### ISSUE THREAD

**Issue by Gabriel-githud** [AssetRipper/AssetRipper#1532] opened 2024-10-20 20:07 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://www.mediafire.com/file/s6iiwmr0vwus3b7/Cube+Runners+VR+V2.apk/file

### Which Unity version did this occur on?

Can't Figure It Out Because I Usually Figure It Out Using AssetRipper

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

When Ripping The APK It Keeps Giving
System.Exception: Read 513 but expected 528 while reading bundle metadata
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadMetadata(Stream, Int32) + 0x27a
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.ReadFileStreamMetadata(Stream, Int64) + 0xc9
   at AssetRipper.IO.Files.BundleFiles.FileStream.FileStreamBundleFile.Read(SmartStream) + 0x88
   at AssetRipper.Import.Structure.Platforms.PlatformGameStructure.GetUnityVersionFromBundleFile(String) + 0x2a
   at AssetRipper.Import.Structure.Platforms.PlatformGameStructure.GetUnityVersionFromDataDirectory(String) + 0x6f
   at AssetRipper.Import.Structure.Platforms.AndroidGameStructure..ctor(String, String) + 0x1cc
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckAndroid(List`1, AndroidGameStructure&) + 0xa9
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckPlatform(List`1, PlatformGameStructure&, MixedGameStructure&) + 0xb4
   at AssetRipper.Import.Structure.GameStructure..ctor(List`1, CoreConfiguration) + 0x6f
   at AssetRipper.Import.Structure.GameStructure.Load(IEnumerable`1, CoreConfiguration) + 0x35
   at AssetRipper.Export.UnityProjects.ExportHandler.Load(IReadOnlyList`1) + 0x1a3
   at AssetRipper.GUI.Web.GameFileLoader.LoadAndProcess(IReadOnlyList`1) + 0x41
   at AssetRipper.GUI.Web.Pages.Commands.LoadFile.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x132
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__6`1.MoveNext() + 0xaf
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x9f

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/17451906/AssetRipper.log)

**Comment by nightfallenxyz** [comment] 2024-11-03 17:27
Same issue.

**Comment by BugEPB626** [comment] 2024-11-03 19:34
Same.

**Comment by ds5678** [comment] 2024-11-03 21:44
Duplicate of #1470

**Closed by ds5678** 2024-11-03 21:44 UTC
Labels: bug
