### ISSUE TITLE
[Other]: The Last Time u didn't understand me 

### ISSUE THREAD

**Issue by JeanTheFungle** [AssetRipper/AssetRipper#1207] opened 2024-02-20 14:58 UTC
### Describe the issue

hi the last time in that old issue i wante tell you is assetripper can now extract il2cpp script not empty like olders version

**Comment by ds5678** [comment] 2024-02-20 15:51
Duplicate of https://github.com/SamboyCoding/Cpp2IL/issues/223

**Closed by ds5678** 2024-02-20 15:51 UTC
