### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LievreAI** [AssetRipper/AssetRipper#904] opened 2023-07-12 23:00 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

https://steamdb.info/app/1895630/

### Which Unity version did this occur on?

Unity 2021.3.0

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

when i try to decompile the game using asset ripper the console return error 
images attached 
![Screenshot 2023-07-13 015617](https://github.com/AssetRipper/AssetRipper/assets/84988313/a2aff25d-d887-4d2f-91a3-c5b38457dd4b)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12033989/AssetRipper.log)

**Comment by ds5678** [comment] 2023-07-13 01:18
Duplicate of #595

**Closed by ds5678** 2023-07-13 01:18 UTC
Labels: bug

**Comment by JeanAU** [comment] 2023-08-23 14:54
Duplicate of #1000
