### ISSUE TITLE
[Enhancement]: Build LightingData.assets

### ISSUE THREAD

**Issue by Gyron777** [AssetRipper/AssetRipper#591] opened 2022-10-28 23:12 UTC
### Describe the new feature or enhancement

Hello guys,I have a problem with restoring lighting data when unpacking resources, i was able to find lightmaps among textures folder to find parts of data blocks but when trying to restore file lightingData.asset i am facing problem of missing UV unwrapping data for Lightmap-0_comp_light.exr?
I could rebake the map, but I don't know the parameters because it looks like unity cuts off some of the data in lightingSettins.lighting when exporting project.

**Comment by ds5678** [comment] 2022-10-28 23:28
Duplicate of #553, which has already been implemented.

**Closed by ds5678** 2022-10-28 23:28 UTC
Labels: enhancement
