### ISSUE TITLE
[Bug]: Import : Error during reading of asset type Material. V: 2021.2.17f1 P: StandaloneWinPlayer N: unity default resources Path: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by e-ed** [AssetRipper/AssetRipper#1218] opened 2024-02-27 05:05 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Erenshor Demo](https://steamdb.info/app/2522260/)

### Which Unity version did this occur on?

2021.2.17f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whenever I click "open folder" or "open file" and assetripper tries to do it's magic and load all the assets, I'm getting an error like described in the title:
```
Import : Error during reading of asset type Material. V: 2021.2.17f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ThrowHelper.ThrowArgumentOutOfRangeException() + 0x24
   at AssetRipper.IO.Endian.EndianSpanReader.ReadBytesExact(Int32) + 0x52
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String() + 0x40
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Map_Utf8StringAlign_Single(AssetDictionary`2, EndianSpanReader&) + 0x84
   at AssetRipper.SourceGenerated.Subclasses.UnityPropertySheet.UnityPropertySheet_2021.ReadRelease(EndianSpanReader&) + 0x30
   at AssetRipper.SourceGenerated.Classes.ClassID_21.Material_2021.ReadRelease(EndianSpanReader&) + 0x114
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment`1, UnityVersion, String&) + 0x182
Import : Error during reading of asset type Material. V: 2021.2.17f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ThrowHelper.ThrowArgumentOutOfRangeException() + 0x24
   at AssetRipper.IO.Endian.EndianSpanReader.ReadBytesExact(Int32) + 0x52
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String() + 0x40
   at AssetRipper.SourceGenerated.Subclasses.BuildTextureStackReference.BuildTextureStackReference.ReadRelease(EndianSpanReader&) + 0x15
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1, EndianSpanReader&) + 0x4b
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment`1, UnityVersion, String&) + 0x182
```
Decided to open an issue in this repo because I tried to ignore the error and import the project to Unity but ended up with a bunch of random crashes.

### Relevant log output

System : AssetRipper
System : System Version: Microsoft Windows NT 10.0.22631.0
System : Operating System: Windows x64
System : AssetRipper Version: 1.0.8.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Tue Feb 27 07:57:00 UTC 2024
System : UTC Compile Time: Mon Feb 26 06:21:50 UTC 2024
General : Configuration Settings:
General : ExportRootPath: C:\Users\Eduardo\Desktop\AssetRipper_win_x64\Ripped
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : BundledAssetsExportMode: GroupByAssetType
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: True
General : EnableAssetDeduplication: True
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
Import : Attempting to read files from C:\Users\Eduardo\Desktop\erenshor demo 2\Erenshor Demo
Import : PC game structure has been found at 'C:\Users\Eduardo\Desktop\erenshor demo 2\Erenshor Demo'
Import : Collecting game files...
Import : Game file 'globalgamemanagers' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
Import : Game file 'level2' has been found
Import : Game file 'level3' has been found
Import : Collecting Streaming Assets...
Import : Files use the 'Mono' scripting backend.
Import : During Mono initialization, found 111 assemblies
Import [Error] : Error during reading of asset type Material. V: 2021.2.17f1 P: StandaloneWinPlayer N: unity default resources Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ThrowHelper.ThrowArgumentOutOfRangeException() + 0x24
   at AssetRipper.IO.Endian.EndianSpanReader.ReadBytesExact(Int32) + 0x52
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String() + 0x40
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_Map_Utf8StringAlign_Single(AssetDictionary`2, EndianSpanReader&) + 0x84
   at AssetRipper.SourceGenerated.Subclasses.UnityPropertySheet.UnityPropertySheet_2021.ReadRelease(EndianSpanReader&) + 0x30
   at AssetRipper.SourceGenerated.Classes.ClassID_21.Material_2021.ReadRelease(EndianSpanReader&) + 0x114
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment`1, UnityVersion, String&) + 0x182
Import [Error] : Error during reading of asset type Material. V: 2021.2.17f1 P: StandaloneWinPlayer N: unity default resources Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at System.ThrowHelper.ThrowArgumentOutOfRangeException() + 0x24
   at AssetRipper.IO.Endian.EndianSpanReader.ReadBytesExact(Int32) + 0x52
   at AssetRipper.IO.Endian.EndianSpanReader.ReadUtf8String() + 0x40
   at AssetRipper.SourceGenerated.Subclasses.BuildTextureStackReference.BuildTextureStackReference.ReadRelease(EndianSpanReader&) + 0x15
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList`1, EndianSpanReader&) + 0x4b
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment`1, UnityVersion, String&) + 0x182
Import : Finished reading files
Processing : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
Processing : Lighting Data Assets
Processing : Finished processing assets

**Comment by ds5678** [comment] 2024-02-27 13:04
Duplicate of #595

**Closed** 2024-02-27 13:04 UTC
Labels: bug
