### ISSUE TITLE
[Enhancement]: Move entire temporary folder location to AssetRipper folder location

### ISSUE THREAD

**Issue by Wanja01YT** [AssetRipper/AssetRipper#1077] opened 2023-10-21 20:57 UTC
### Describe the new feature or enhancement

Exporting big Unity games can get filesize-heavy, which polluted my C: drive to a point of less than a gigabyte of free space. When extracting some larger games, I get the following error:

`System.IO.IOException: There is not enough space on the disk. : 'C:\Users\wanja\AppData\Local\Temp\tmpA8D8.tmp'`

Moving the entire temp location into the folder of AssetRipper (which could easily be moved to a different drive) would solve this error in many cases for me and other users

**Comment by ds5678** [comment] 2023-10-21 21:23
Duplicate of #938

**Closed by ds5678** 2023-10-21 21:23 UTC
Labels: enhancement
