### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sgnme** [AssetRipper/AssetRipper#1059] opened 2023-10-04 20:47 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Vegas Infinite](https://store.steampowered.com/agecheck/app/886250/)

### Which Unity version did this occur on?

2022.3.7f1 (b16b3b16c7a0)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Asset riper is unable to open the level11 file at all.

### Relevant log output

```System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.19045.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Wed Oct  4 20:37:35 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: D:\assetripper\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from D:\steamapp\steamapps\common\PokerStars VR\PokerStarsVR_Data\level11
Import : Game file 'level11' has been found
Import : Mixed game structure has been found at D:\steamapp\steamapps\common\PokerStars VR\PokerStarsVR_Data\level11
Import : Files use the 'Unknown' scripting backend.
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
System.ArgumentException: Unknown attribute 2715863291 for ParticleSystem
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 169
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 235
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 61
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.Process(IAnimationClip clip, PathChecksumCache checksumCache) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 46
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 85
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 21```

**Comment by ds5678** [comment] 2023-10-04 21:14
Duplicate of #1025

**Closed by ds5678** 2023-10-04 21:14 UTC
Labels: bug
