### ISSUE TITLE
[Question]: Export: Could not resolve assembly. how i can fix?

### ISSUE THREAD

**Issue by Sus228777** [AssetRipper/AssetRipper#639] opened 2022-12-15 12:57 UTC
### Question

Hello guys, do you know how to fix it?

```
Export : Exporting scripts...
Export : Decompiling AlmostEngine
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Decompiling AlmostEngine.Shared
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Decompiling Assembly-CSharp
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Decompiling com.rlabrecque.steamworks.net
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Decompiling com.unity.multiplayer-hlapi.Runtime
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
Export : Decompiling NavMeshComponents
Export : Could not resolve assembly: System.Runtime.InteropServices
Export : Could not resolve assembly: System.Runtime.CompilerServices.Unsafe
```

![a](https://user-images.githubusercontent.com/120651331/207867950-6d864e23-c196-46d3-a691-d1e5a3e91a7e.PNG)

**Comment by ds5678** [comment] 2022-12-16 17:38
Duplicate of #542

**Closed by ds5678** 2022-12-16 17:38 UTC
