### ISSUE TITLE
[Bug]: `AssetDictionary<FastPropertyName, UnityTexEnv> Material.TexEnvs` has bad Yaml formatting on Unity 4

### ISSUE THREAD

**Issue by Prosopho** [AssetRipper/AssetRipper#1045] opened 2023-09-22 16:42 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Not applicable

### Which Unity version did this occur on?

4.0.0-4.7.2

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

The materials lose all the attached textures and shader properties. This was done in an game made with 4.3.2 and opened within the same version, but it should be applicable for all unity 4 versions.
![image](https://github.com/AssetRipper/AssetRipper/assets/109369903/05064401-22ce-4f27-b181-3428427d94e9)
![image](https://github.com/AssetRipper/AssetRipper/assets/109369903/f3191753-d174-475f-ba40-c6c52b521d22)

Before and after of the material.
(Original material vs Correct texture assigned.)
![image](https://github.com/AssetRipper/AssetRipper/assets/109369903/f677acca-5c63-4761-91f9-bd6d96b2b553)

I found that if i moved the **data** and **first** section from the fixed material to the original or other material, it'd solve it at minimum. 

I saw this being mentioned in the discord but it got lost in the void.

**Comment by ds5678** [comment] 2023-10-12 15:11
Duplicate of #821

**Closed by ds5678** 2023-10-12 15:11 UTC
Labels: bug, export
