### ISSUE TITLE
[Bug]: System.ArgumentException: SerializedFile with name XXXXXXXXXXXXXXX conflicts with file at YYYYYYYYYY  (Parameter 'file')

### ISSUE THREAD

**Issue by reidsneo** [AssetRipper/AssetRipper#470] opened 2022-07-20 02:46 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

https://play.google.com/store/apps/details?id=com.playwith.sealm.tw.googl&hl=en&gl=US
https://play.google.com/store/apps/details?id=com.play.rosea&hl=en&gl=US

### Which Unity version did this occur on?

2021

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Cannot import project, project crashed during import folder

### Relevant log output

![image](https://user-images.githubusercontent.com/12298979/179884918-a049ba41-0035-405e-8c34-8f8cdaa25611.png)
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9146086/AssetRipper.log)

**Comment by reidsneo** [comment] 2022-07-20 08:52
hey it seem when I open folder in
files > Bundle or files > UnityCache it is working 

but in root directory
com.play.rosea
  - cache
  - files

is always crashing

**Comment by ds5678** [comment] 2022-07-20 19:29
Duplicate of #281

**Closed by ds5678** 2022-07-20 19:29 UTC
Labels: bug
