### ISSUE TITLE
[Enhancement]: Native game file export for all versions of Unity 5

### ISSUE THREAD

**Issue by Jamesthe1** [AssetRipper/AssetRipper#267] opened 2022-02-16 19:33 UTC
### Describe the new feature or enhancement

**What's the suggestion?**
The exporter should use the native version of assets for Unity 5.

**Why?**
The game only exports to Unity version 2017 as its lowest version. This causes problems, especially for anything below Unity 5.5 as said version changed the GameObject format. This can be frustrating for testing compatibility with existing scenes, and modifying/taking apart other prefabs. If I plan to use this as a development environment for mods (the game I'm working with is in Unity 5.4), it would be better to have this support.

**Comment by Jamesthe1** [comment] 2022-02-16 19:36
Logs: [AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8082944/AssetRipper.log)

**Comment by ds5678** [comment] 2022-02-16 19:51
Duplicate of #164, which is in progress

**Closed** 2022-02-16 19:51 UTC
Labels: enhancement
