### ISSUE TITLE
[Enhancement]: Bring back the 'export all assets of selected type' feature ;)

### ISSUE THREAD

**Issue by Zbuffers** [AssetRipper/AssetRipper#1519] opened 2024-10-12 13:49 UTC
### Describe the new feature or enhancement

Hi ;)
Would be nice to have this feature that existed before the new UI. 
That would spare quite some time instead of exporting the whole game for just a few files.

Kind regards,
Zbuffer

**Comment by ds5678** [comment] 2024-11-22 03:40
Duplicate of #1340

**Closed by ds5678** 2024-11-22 03:40 UTC
Labels: enhancement
