### ISSUE TITLE
[Bug]: Native Crash

### ISSUE THREAD

**Issue by cualquiercosa327** [AssetRipper/AssetRipper#339] opened 2022-03-28 12:39 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.12f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Hello, when I try to extract all the files it always crash when it is on 3% or on the 15%.

It is Disco Elysium Director Cut with the latest update (both pc and Switch version).

I tried with an older pc version of the game and it worked.

Note: this game uses an external pluggin for the textures and I was successful with the old version moving the folder where the assets of this pluggin to another place and letting it as if.

**Comment by cualquiercosa327** [comment] 2022-03-28 14:51
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8363875/AssetRipper.log)

**Comment by ds5678** [comment] 2022-03-28 21:07
This looks like a duplicate of #81. There are plans to remove all native dependencies, but this is no small feat.

**Comment by cualquiercosa327** [comment] 2022-03-29 00:53
Is it related only  with the  textures?

**Comment by ds5678** [comment] 2022-03-29 05:56
I've also seen a situation where something similar can happen with audio because we use ogg binaries, but that's very rare.

This can only happen with a select portion of textures that use the native binary. A contributor is working on something that might help alleviate some of this.

**Comment by cualquiercosa327** [comment] 2022-03-29 16:58
The weirdest part, an older version on pc (few moths before this one) use 2020.2.3f1, most of the data are the same (they simply moved a few and add a little) and it doesn't crash.

I am interested on this latest as it is the same they use on console verdion

**Comment by ds5678** [comment] 2022-06-30 21:45
duplicate of #81

**Closed by ds5678** 2022-06-30 21:45 UTC
Labels: bug, textures
