### ISSUE TITLE
[Bug]: Asset doesn't belong to this serialized file or its dependencies

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#617] opened 2022-11-27 07:57 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Adventure Ages

### Which Unity version did this occur on?

2019.4.26

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The following error from the log appears the moment you try to export all

General : About to begin export to V:\AdventureAges\AssetRipperExport638051719860010734
General : Removing any files from a previous export...
Export : Attempting to export assets to V:\AdventureAges\AssetRipperExport638051719860010734...
Export : Starting pre-export
Export : Starting export
Export : Game files have these Unity versions: 2019.4.26f1
Export : Exporting to Unity version 2019.4.26f1
Export : Preparing for export...
Export : Preparing for export...
[Error] : System.Exception: Asset doesn't belong to this serialized file or its dependencies
   at AssetRipper.Core.Parser.Files.SerializedFiles.SerializedFile.CreatePPtr[T](T asset) in D:\a\AssetRipper\AssetRipper\AssetRipper.Fundamentals\Parser\Files\SerializedFiles\SerializedFile.cs:line 148
   at AssetRipper.Library.Exporters.Textures.YamlSpriteExporter.ConvertPPtr[T](IPPtr`1 pptr, ISpriteAtlas atlas, ISprite sprite) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\YamlSpriteExporter.cs:line 104
   at AssetRipper.Library.Exporters.Textures.YamlSpriteExporter.CreateCollection(VirtualSerializedFile virtualFile, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Exporters\Textures\YamlSpriteExporter.cs:line 45
   at AssetRipper.Core.Project.ProjectExporter.CreateCollection(VirtualSerializedFile file, IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 128
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, IEnumerable`1 files, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 207
   at AssetRipper.Core.Project.ProjectExporter.Export(GameCollection fileCollection, CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Project\ProjectExporter.cs:line 172
   at AssetRipper.Core.Structure.GameStructure.GameStructure.Export(CoreConfiguration options) in D:\a\AssetRipper\AssetRipper\AssetRipper.Core\Structure\GameStructure\GameStructure.cs:line 97
   at AssetRipper.Library.Ripper.ExportProject(String exportPath, Func`2 filter) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 181
   at AssetRipper.Library.Ripper.ExportProject(String exportPath) in D:\a\AssetRipper\AssetRipper\AssetRipper.Library\Ripper.cs:line 163
   at AssetRipper.GUI.Managers.UIExportManager.ExportInternal(Ripper ripper, String toRoot, Action onSuccess, Action`1 onError) in D:\a\AssetRipper\AssetRipper\AssetRipper.GUI\Managers\UIExportManager.cs:line 52

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10097775/AssetRipper.log)

**Comment by ds5678** [comment] 2022-11-27 19:23
Duplicate of #556

**Closed by ds5678** 2022-11-27 19:23 UTC
Labels: bug

**Comment by cyberangel67** [comment] 2022-11-27 23:46
You say completed, does this mean there is an update coming soon with this fix?

**Comment by ds5678** [comment] 2022-11-27 23:58
There's only two options when I press the close button: completed or not planned.

**Comment by ds5678** [comment] 2022-12-01 03:43
Try https://github.com/AssetRipper/AssetRipper/actions/runs/3588783128 and let me know how it goes.

**Comment by cyberangel67** [comment] 2022-12-08 13:23
sorry for not getting back to you sooner, but I do not see any issues now.
