### ISSUE TITLE
[Bug]: Loading textures crashes assetripper

### ISSUE THREAD

**Issue by IHAVEALOTTODO** [AssetRipper/AssetRipper#458] opened 2022-07-08 14:02 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Angry birds 2

### Which Unity version did this occur on?

Unknown

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I loaded the textures and it does not respond and crashes

**Comment by IHAVEALOTTODO** [comment] 2022-07-08 14:03
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9072637/AssetRipper.log)

**Comment by ds5678** [comment] 2022-07-08 18:56
Duplicate of #81, which relates to #447 and #448. These are being actively worked on.

**Closed by ds5678** 2022-07-08 18:56 UTC
Labels: bug
