### ISSUE TITLE
[Bug]: Always getting this error during importing - Applies to apk files

### ISSUE THREAD

**Issue by MetaMysteries8** [AssetRipper/AssetRipper#1255] opened 2024-03-19 01:55 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Every time when using this tool, I always get this error (note this is only when using apks) `Import : Unable to read MonoBehaviour Structure, because script UnityEngine.GUISkin layout mismatched binary content (ArgumentOutOfRangeException).`
Not only that, but it seems that every version I use it always does this.

I don't know what issues is going on

### Which Unity version did this occur on?

2020.3.47f1 (though it seems to occur no matter what version the apk, unity editor, and other apps. is this due to issues with mono?)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Whenever

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14644298/AssetRipper.log)

**Comment by ds5678** [comment] 2024-03-23 21:37
Duplicate of #1202

**Closed by ds5678** 2024-03-23 21:37 UTC
Labels: bug
