### ISSUE TITLE
[Bug]: Texture2D Image Glitch

### ISSUE THREAD

**Issue by medAndro** [AssetRipper/AssetRipper#725] opened 2023-02-07 19:16 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Yuru CampΔ Have a nice day! (Nintendo Switch)

### Which Unity version did this occur on?

2020.3.14

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

![cap175](https://user-images.githubusercontent.com/88672474/217341400-4222dc21-2361-4c5c-8310-80981c307ab8.png)
![criware1920x1080sw-CAB-a432eb338d551b13f6b1a7512a1bd230-48288472322925456](https://user-images.githubusercontent.com/88672474/217342105-3ad7d583-02e0-4ace-993f-4d15ca3e81e8.png)
The second image shows a correctly extracted image from [UABE Avalonia](https://github.com/nesrak1/UABEA). 
In AssetRipper, it is corrupted as shown in the first screenshot. 
The corresponding unity3d file is attached below.
[ci.zip](https://github.com/AssetRipper/AssetRipper/files/10678600/ci.zip)

**Comment by ds5678** [comment] 2023-02-07 21:37
Duplicate of #629

**Closed by ds5678** 2023-02-07 21:37 UTC
Labels: bug
