### ISSUE TITLE
[Bug]: Script Export Error

### ISSUE THREAD

**Issue by cyberangel67** [AssetRipper/AssetRipper#58] opened 2021-08-24 02:45 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2020.3.7f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Failed to export game content: The given key 'T' was not present in the dictionary.
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7036108/AssetRipper.log)

**Comment by ds5678** [comment] 2021-08-24 04:52
I'm currently investigating a related issue with the GUI. After I fix it, we can revisit this.

**Comment by ds5678** [comment] 2021-08-24 05:08
Just for my own information, can you try the latest alpha build and send me a new log?
https://github.com/ds5678/AssetRipper/actions/runs/1161300940

**Comment by cyberangel67** [comment] 2021-08-24 06:53
Sure here is the log file with the latest alpha build.
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7037039/AssetRipper.log)

**Comment by ds5678** [comment] 2021-08-28 01:15
Can you retry with `0.1.5.1` and send me a new log?

**Comment by cyberangel67** [comment] 2021-08-28 05:28
Same error and log attached

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7070193/AssetRipper.log)

**Comment by cyberangel67** [comment] 2021-09-24 20:51
I have a project that I created that can duplicate this, if you want the source code let me know.

**Comment by ds5678** [comment] 2021-09-24 22:23
Yes, that would be helpful

**Comment by cyberangel67** [comment] 2021-09-24 23:06
[Nested Scriptable.zip](https://github.com/ds5678/AssetRipper/files/7228727/Nested.Scriptable.zip)

This generates the same key issue, whether it fixes all cases of it or not, I don't know. But it might be a start.

You should be able to just open this up, the asset might not be there if it is not. Then you go to Assets menu =>stata/ContainerDamageType to create the Scriptable Object. Then with the SO selected you can go to the hierachy and use the context menu to  Make New. This should add another SO to the asset.

From here you can just build this to a Standalone build.

When I tried to rip this, I got the key duplicated message. Oh I just realised this is a different error message, maybe it is related somehow.

**Comment by ds5678** [comment] 2021-09-26 08:44
I'm going to need a new log

**Comment by ds5678** [comment] 2022-02-25 21:32
closing as a duplicate of #227

**Closed by ds5678** 2022-02-25 21:32 UTC
Labels: bug, export
