### ISSUE TITLE
[Question]: I tried to extract an audioclip from an unity asset bundle. It failed and the AssetsRipper shows unity version be Unity 0.0.0a0. I wonder why  

### ISSUE THREAD

**Issue by LighttttTL** [AssetRipper/AssetRipper#800] opened 2023-04-17 18:51 UTC
### Question

I tried to extract an audioclip from an unity asset bundle. It failed and the AssetsRipper shows unity version be Unity 0.0.0a0. 
Is it a bug or do I mistake the type of the file? 
This is a file I downloaded from the server of a unity game. The version of Unity the game application used is Unity 2021.3.13. 
The game changed its server recently, and previously the same type of file can be Extracted by both AssetRipper and AssetStudio. 
![Picture](https://user-images.githubusercontent.com/129585751/232582240-28509155-dda3-4243-bf44-1a91ba3becee.jpg)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by HikariChen** [comment] 2023-04-17 18:57
System : AssetRipper GUI Version
System : System Version: Microsoft Windows NT 10.0.22621.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.1.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Mon Apr 17 18:54:25 UTC 2023
System : UTC Compile Time: Sat Apr  8 17:28:41 UTC 2023
System : Loading locale en_US.json
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : ExportRootPath: D:\GAME\EXTRACT
\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Decompiled
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : Attempting to read files from C:\Users\quanz\Downloads\bgm
Import : Game file 'bgm' has been found
Import : Mixed game structure has been found at C:\Users\quanz\Downloads\bgm
Import : Files use the 'Unknown' scripting backend.
Import [Warning] : The game structure processor could not find any valid assets.
General : Finished reading files
General : Processing assemblies...
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Editor Format Conversion
General : Finished processing assets

**Comment by ds5678** [comment] 2023-04-17 22:10
Duplicate of #252

**Closed by ds5678** 2023-04-17 22:10 UTC
