### ISSUE TITLE
[Bug]: AbstractClassException: Abstract class could not be created

### ISSUE THREAD

**Issue by SospectGuy58** [AssetRipper/AssetRipper#1001] opened 2023-08-22 13:18 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Hello Engineer (https://steamdb.info/app/1856190/)

### Which Unity version did this occur on?

2022.2.2f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Program crashes while creating file collection when loading game's content;
```
AssetRipper.SourceGenerated.Exceptions.AbstractClassException: Abstract class could not be created
   at AssetRipper.SourceGenerated.Classes.ClassID_320.PlayableDirector.Create(AssetInfo info, UnityVersion version)
   at AssetRipper.SourceGenerated.AssetFactory.Create(AssetInfo info, UnityVersion version)
   at AssetRipper.Import.AssetCreation.GameAssetFactory.ReadAsset(AssetInfo assetInfo, ReadOnlyArraySegment`1 assetData, SerializedType assetType) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\AssetCreation\GameAssetFactory.cs:line 56
   at AssetRipper.Assets.Collections.SerializedAssetCollection.ReadData(SerializedAssetCollection collection, SerializedFile file, AssetFactoryBase factory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Collections\SerializedAssetCollection.cs:line 76
   at AssetRipper.Assets.Collections.SerializedAssetCollection.FromSerializedFile(Bundle bundle, SerializedFile file, AssetFactoryBase factory, UnityVersion defaultVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Collections\SerializedAssetCollection.cs:line 71
   at AssetRipper.Assets.Bundles.SerializedBundle.FromFileContainer(FileContainer container, AssetFactoryBase factory, UnityVersion defaultVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\SerializedBundle.cs:line 35
   at AssetRipper.Assets.Bundles.GameBundle.InitializeFromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider, UnityVersion defaultVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 42
   at AssetRipper.Assets.Bundles.GameBundle.FromPaths(IEnumerable`1 paths, AssetFactoryBase assetFactory, IDependencyProvider dependencyProvider, IResourceProvider resourceProvider, UnityVersion defaultVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Assets\Bundles\GameBundle.FromPaths.cs:line 24
   at AssetRipper.Import.Structure.GameStructure.InitializeGameCollection(UnityVersion defaultVersion) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 79
   at AssetRipper.Import.Structure.GameStructure..ctor(List`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 39
   at AssetRipper.Import.Structure.GameStructure.Load(IEnumerable`1 paths, CoreConfiguration configuration) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Import\Structure\GameStructure.cs:line 59
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 111
   at AssetRipper.GUI.Managers.UIImportManager.ImportFromPathInternal(Ripper ripper, String[] paths, Action`1 onComplete, Action`1 onError) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\Managers\UIImportManager.cs:line 20
```

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12408981/AssetRipper.log)

**Comment by ds5678** [comment] 2023-08-22 14:39
Duplicate of #252

**Closed by ds5678** 2023-08-22 14:38 UTC
Labels: bug
