### ISSUE TITLE
[Question]: How to output the file of MonoBehaviour into json?

### ISSUE THREAD

**Issue by pet345** [AssetRipper/AssetRipper#1024] opened 2023-09-06 10:39 UTC
### Question

Because we need to decode the pictures drawn with atlas
Both Texture2D (png) and MonoBehaviour (json) are required
But MonoBehaviour can only output yaml (I don’t know what it is used for)
Originally I was using asset studio, but it was determined to stop updating from the beginning of this year (only supported until 2022.1.X)
The game I want to unpack is 2022.3.X, and the calculation of Texture2D will cause a crash.

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by pet345** [comment] 2023-09-06 10:41
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12536440/AssetRipper.log)

**Comment by ds5678** [comment] 2023-09-06 10:45
Duplicate of #861

**Closed** 2023-09-06 10:45 UTC
