### ISSUE TITLE
[Bug]: System Expection file nor directory doesn't exist

### ISSUE THREAD

**Issue by EditaNEmilis** [AssetRipper/AssetRipper#1384] opened 2024-06-07 19:11 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Five Nights at Cobson's 1.0.4

### Which Unity version did this occur on?

2021.3.26f1 (a16dc32e0ff2)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

General stuffs managed to load in, but error output from System.Exception when trying to read the file.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/15743954/AssetRipper.log)

**Comment by ds5678** [comment] 2024-07-30 06:10
Duplicate of #1407

**Closed by ds5678** 2024-07-30 06:10 UTC
Labels: bug
