### ISSUE TITLE
[Bug]: Create Vertex Memory Accessors Error

### ISSUE THREAD

**Issue by promiselonely** [AssetRipper/AssetRipper#1144] opened 2023-12-27 11:35 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which Unity version did this occur on?

2021.3.23f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Mesh Export Format:GLB

I am using the latest Alpha Builds version and encountered an error when exporting

### Relevant log output

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Internal.Runtime.CompilerHelpers.ThrowHelpers.ThrowIndexOutOfRangeException() + 0x24
   at SharpGLTF.Geometry.VertexTypes.VertexUtils.CreateVertexMemoryAccessors[TVertex](IReadOnlyList`1, PackedEncoding) + 0x165
   at SharpGLTF.Geometry.PackedPrimitiveBuilder`1.SetStridedVertices(IPrimitiveReader`1, PackedEncoding) + 0x3e
   at SharpGLTF.Geometry.PackedMeshBuilder`1.<CreatePackedMeshes>d__0.MoveNext() + 0x356
   at System.Collections.Generic.List`1..ctor(IEnumerable`1) + 0xed
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1) + 0x3d
   at SharpGLTF.Schema2.Toolkit.CreateMeshes[TMaterial](ModelRoot, Converter`2, SceneBuilderSchema2Settings, IMeshBuilder`1[]) + 0x24f
   at SharpGLTF.Scenes.Schema2SceneBuilder.AddGeometryResources(ModelRoot, IEnumerable`1, SceneBuilderSchema2Settings) + 0x368
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2(IEnumerable`1, SceneBuilderSchema2Settings) + 0x66
   at SharpGLTF.Scenes.SceneBuilder.ToGltf2() + 0x40
   at AssetRipper.Export.UnityProjects.Models.GlbModelExporter.ExportBinary(IEnumerable`1, Boolean) + 0x2d6
   at AssetRipper.Export.UnityProjects.Models.GlbModelExporter.Export(IExportContainer, IEnumerable`1, String) + 0x37
   at AssetRipper.Export.UnityProjects.AssetExportCollection`1.Export(IExportContainer, String) + 0xec
   at AssetRipper.Export.UnityProjects.ProjectExporter.Export(GameBundle, CoreConfiguration) + 0x17c
   at AssetRipper.Export.UnityProjects.Ripper.ExportProject(GameData, LibraryConfiguration, String, IEnumerable`1, Action`1) + 0x1a0
   at AssetRipper.GUI.Web.ExportHandler.Export(GameData, String) + 0x48
   at AssetRipper.GUI.Web.Pages.Commands.Export.AssetRipper.GUI.Web.Pages.ICommand.Start(HttpRequest) + 0x53
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext) + 0x299
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x2a

**Comment by ds5678** [comment] 2023-12-27 13:03
Duplicate of #1132

**Closed** 2023-12-27 13:04 UTC
Labels: bug
