### ISSUE TITLE
[Question]: Why is everything invisible in the decompiled project

### ISSUE THREAD

**Issue by Teapottt** [AssetRipper/AssetRipper#1299] opened 2024-04-16 18:45 UTC
### Question

Everything is invisible in editor mode

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/15001439/AssetRipper.log)

**Comment by ds5678** [comment] 2024-04-17 03:11
My intuition says that it's because you probably changed the unity version.

**Comment by Teapottt** [comment] 2024-04-17 11:30
> My intuition says that it's because you probably changed the unity version.
No, I installed the exact same version

**Comment by ds5678** [comment] 2024-04-17 15:54
No idea then

**Comment by ds5678** [comment] 2024-04-17 15:58
If the cause for your experience is not discovered in the near future, I will close this issue for organizational reasons. If I close it, it may be reopened at anytime with new information.

**Closed** 2024-04-20 15:44 UTC
