### ISSUE TITLE
[Bug]: VRCA file can't be extracted properlly

### ISSUE THREAD

**Issue by ketoro337** [AssetRipper/AssetRipper#1146] opened 2023-12-29 14:50 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Vrchat 

### Which Unity version did this occur on?

I assume 2019 ?

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

When extraction of VRCA file it spits out 
General [Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
Then the program stops and the extraction fails.

### Relevant log output

System : AssetRipper Console Version
System : System Version: Microsoft Windows NT 10.0.22631.0
System : Operating System: Windows 64 bit
System : AssetRipper Version: 0.3.4.0
System : AssetRipper Build Type: Release Published
System : UTC Current Time: Fri Dec 29 14:44:23 UTC 2023
System : UTC Compile Time: Tue Sep  5 05:23:26 UTC 2023
General : Configuration Settings:
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : ExportRootPath: C:\Users\Nuggy\Desktop\AssetRipper_win_x64\Ripped
General : ExportDependencies: False
General : BundledAssetsExportMode: DirectExport
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: False
General : IgnoreEngineAssets: False
General : Attempting to read files from C:\Users\Nuggy\Desktop\Release (2)\VRCA\gigarusk-avtr_de8e908c-2c93-4a06-b7c0-77f98c81fcc1_pc.vrca
Import : Game file 'gigarusk-avtr_de8e908c-2c93-4a06-b7c0-77f98c81fcc1_pc.vrca' has been found
Import : Mixed game structure has been found at C:\Users\Nuggy\Desktop\Release (2)\VRCA\gigarusk-avtr_de8e908c-2c93-4a06-b7c0-77f98c81fcc1_pc.vrca
Import : Files use the 'Unknown' scripting backend.
Import [Warning] : Dependency 'Resources/unity_builtin_extra' wasn't found
Import [Warning] : Dependency 'Library/unity default resources' wasn't found
General : Finished reading files
General : Processing loaded assets...
Processing : Creating Scene Definitions
Processing : Main Asset Pairing
Processing : Lighting Data Assets
Processing : Reconstruct AnimatorController Assets
Processing : Reconstruct AudioMixer Assets
Processing : Editor Format Conversion
General [Error] : System.ArgumentException: Unknown attribute 1173142787 for ParticleSystem
   at AssetRipper.Processing.AnimationClips.CustomCurveResolver.ToAttributeName(BindingCustomType type, UInt32 attribute, String path) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\CustomCurveResolver.cs:line 169
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.AddCustomCurve(IAnimationClipBindingConstant bindings, IGenericBinding binding, String path, Single time, Single value) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 235
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessStreams(IReadOnlyList`1 streamFrames, IAnimationClipBindingConstant bindings, Single sampleRate) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 125
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.ProcessInner() in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 61
   at AssetRipper.Processing.AnimationClips.AnimationClipConverter.Process(IAnimationClip clip, PathChecksumCache checksumCache) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\AnimationClips\AnimationClipConverter.cs:line 46
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Convert(IUnityObjectBase asset) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 112
   at AssetRipper.Processing.Editor.EditorFormatProcessor.Process(GameData gameData) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Processing\Editor\EditorFormatProcessor.cs:line 76
   at AssetRipper.Export.UnityProjects.Ripper.Load(IReadOnlyList`1 paths) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.Export.UnityProjects\Ripper.cs:line 119
   at AssetRipper.GUI.ConsoleApp.Run(IReadOnlyList`1 filesToExport, String outputDirectory) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 128
   at AssetRipper.GUI.ConsoleApp.ParseArgumentsAndRun(String[] args) in D:\a\AssetRipper\AssetRipper\Source\AssetRipper.GUI\ConsoleApp.cs:line 43

**Comment by ds5678** [comment] 2023-12-29 15:40
Use a newer version

**Comment by ds5678** [comment] 2023-12-29 17:30
Duplicate of #1025

**Closed by ds5678** 2023-12-29 17:30 UTC
Labels: bug

**Comment by ketoro337** [comment] 2023-12-31 07:41
I was using the latest version. Tho, i just tried it again and no dice unfortunatly. Do you perhaps want to try it with my VRCA file ? I could provide it.
