### ISSUE TITLE
[Bug]: System.Exception: atlas is not the same as mappedAtlas

### ISSUE THREAD

**Issue by SuperSleepMan** [AssetRipper/AssetRipper#1485] opened 2024-09-07 05:45 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Cult of the Lamb
https://steamdb.info/app/1313140/

### Which Unity version did this occur on?

The error occurred during the Processing phase

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

An error occurred while parsing this：

Processing : Lighting Data Assets
[Error] : System.Exception: atlas is not the same as mappedAtlas
   at AssetRipper.Processing.Textures.SpriteInformationObject.AddToDictionary(ISprite, ISpriteAtlas) + 0xa9
   at AssetRipper.Processing.Textures.SpriteProcessor.Process(GameData) + 0x37d
   at AssetRipper.Export.UnityProjects.ExportHandler.Process(GameData) + 0xa2
   at AssetRipper.GUI.Web.GameFileLoader.LoadAndProcess(IReadOnlyList`1) + 0x4f
   at AssetRipper.GUI.Web.Pages.Commands.LoadFolder.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x12f
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__7`1.MoveNext() + 0xaf
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x9f

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/16914843/AssetRipper.log)

**Comment by ds5678** [comment] 2024-09-07 07:22
Duplicate of #740

**Closed by ds5678** 2024-09-07 07:22 UTC
Labels: bug
