### ISSUE TITLE
[Bug]: Animation Decompilation Issue

### ISSUE THREAD

**Issue by DPrison** [AssetRipper/AssetRipper#778] opened 2023-03-26 16:28 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Zumbi Blocks 2 (this aviable in itch.io, using 0.8.1 game version)

### Which Unity version did this occur on?

2020.3.17 (but project exported to 2021.3.18f1)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Some animations decomiples wrong, i already try to decompile anims with devX, and they throw exception like "Incorrect file name" (example name of one animation "Armature|LobbyWalkPistol.anim", i think | char occur error)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11072248/AssetRipper.log)

**Comment by ds5678** [comment] 2023-03-27 01:15
Probably a duplicate of #679

**Comment by ds5678** [comment] 2023-03-27 02:59
@DPrison Unless you show me otherwise, I will assume this issue is a duplicate and close it.

**Comment by ds5678** [comment] 2023-04-07 02:26
Duplicate of #679

**Closed by ds5678** 2023-04-07 02:26 UTC
Labels: bug, animation
