### ISSUE TITLE
[Bug]: When using UnityHub to open the exported project, a pop-up window of Unity Bug Reporter appears.

### ISSUE THREAD

**Issue by CodeEngieer** [AssetRipper/AssetRipper#969] opened 2023-08-04 10:33 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

In the exported project files, there may be some projects that pop up a Unity Bug Reporter and cannot be opened properly during the loading process, while others can be opened normally. Like the example below, if necessary, I can send you the exported project file as an email attachment.

### Which Unity version did this occur on?

Unity Editor 2021.2.3f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![enter description here](https://raw.githubusercontent.com/CodeEngieer/Demo/main/小书匠/1691145060316.png)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12259849/AssetRipper.log)
[shadercompiler-UnityShaderCompiler.exe0.log](https://github.com/AssetRipper/AssetRipper/files/12259850/shadercompiler-UnityShaderCompiler.exe0.log)

**Comment by JonJon565** [comment] 2023-08-04 15:43
try opening with another unity version like 2017 or 2022 or 2018 or 2019
maybe that will fix it

**Comment by ds5678** [comment] 2023-08-04 18:47
This seems like something that would be difficult for me to troubleshoot or reproduce. If you want this to ever be resolved, I will need more useful information on what is actually wrong. For example, #821 is a well written issue.

**Comment by JonJon565** [comment] 2023-08-04 19:05
yes that seems too be the error the prefabs worked on unity 5 but the gui didnt (it worked in 2017 tho) so i was just going too use the prefabs utiny ripper exported

**Comment by JonJon565** [comment] 2023-08-04 19:05
unless there is a fix

**Comment by ds5678** [comment] 2023-08-04 19:16
@JonJon565 how is that related to this issue (shader compilation error)?

**Comment by PatnosDD** [comment] 2023-08-07 10:28
The crash mostly occurs due to LightingData.asset which is probably getting out badly damaged sometimes. Deleting it solves the crash issues in 90% times

**Comment by CodeEngieer** [comment] 2023-08-07 10:50
The problem has been resolved by deleting the corresponding lighting data, including LightSettings, LightData, and LightProbes. The author should mark it as solved. In earlier versions, exporting worked fine, but in the new version, there is a probability of encountering this issue when exporting the source project.

By the way, can the author restore the folder structure corresponding to the exported project for subsequent versions? Currently, every time I open the project, I have to move Unity's default packages to the Packages folder under the root directory and then delete the manifest.json file. Although the project can run, it will throw a Null Pointer Exception. The reason is that, for example:
```csharp
transform.Find("UI/UI_Panel");
GameObject.Find("UI/UI_Panel");
```
Due to the chaotic folder structure, the game objects cannot be found, resulting in a Null Pointer Exception.

**Comment by ds5678** [comment] 2023-08-07 13:27
Duplicate of #811

**Closed by ds5678** 2023-08-07 13:27 UTC
Labels: bug

**Comment by JonJon565** [comment] 2023-08-07 21:43
turns out it was the prefabs

**Comment by JonJon565** [comment] 2023-08-07 21:44
i suggest a addon that does something like force export certain things like prefabs too a certain unity version that is selected

**Comment by JonJon565** [comment] 2023-08-07 21:45
or fix broken gui for unity 5
but i'd prefer the former

**Comment by JonJon565** [comment] 2023-08-07 21:46
wait wrong issue
crap

**Comment by JonJon565** [comment] 2023-08-07 21:47
#970
