### ISSUE TITLE
[Bug]: Corrupted prefabs from ripped unity 4 games after upgrading to unity 5.

### ISSUE THREAD

**Issue by Prosopho** [AssetRipper/AssetRipper#833] opened 2023-05-21 18:49 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Shouldn't maybe be applicable...
https://play.google.com/store/apps/details?id=com.pixel.gun3d (Older versions of the game. (5.1.1 and 10.2.1) downloaded via [aurora store](https://auroraoss.com/) using version codes (133 and 788 respectively.))

### Which Unity version did this occur on?

Game used unity 4.3.2 (5.1.1) and 4.6.9p4 (10.2.1) respectively but should happens on most unity 4.x and 5.x based games.

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After upgrading the ripped game from unity 4 to 5 all the prefabs are corrupted with most if not all of their components removed. This only happens until version 5.4.0 (including the beta version of 5.4.0) where the prefabs aren't corrupted on any version past it. I didn't try too many AssetRipper versions but should be reproducible/happens on all versions past 0.1.9.9. Happens on latest alpha build too for both of the versions. 

This doesn't seem to happen on locally created and upgraded projects just yet...

Edit 1: Upon further investigation animation controllers are corrupted as well and maybe some other assets too...

Edit 2: This happens even with minor version bumps with old unity 5 games as well.

![corrupted](https://github.com/AssetRipper/AssetRipper/assets/109369903/a9e63fa3-6ace-4d98-9052-58032e87eefc)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11525082/AssetRipper.log)

**Comment by ds5678** [comment] 2023-05-23 12:05
Possible duplicate of https://github.com/AssetRipper/AssetRipper/issues/821

**Comment by Prosopho** [comment] 2023-09-21 15:31
Closing this due to lack of info about it and to not clog issues.

**Closed** 2023-09-21 15:31 UTC
Labels: bug

**Comment by ds5678** [comment] 2023-09-21 16:34
I know a little bit more now.

For prefabs, the GameObject format changed substantially at the `5.5.0` boundary. Transform changed in `4.5.0` and `5.3.5`.

There were a lot of changes in Unity 5. The corruption of animator controllers could be similarly explained.

This issue is likely a duplicate of #696.
