### ISSUE TITLE
[Bug]: Unable to read MonoBehaviour, because script layout NestInput mismatches binary content

### ISSUE THREAD

**Issue by pwrmln** [AssetRipper/AssetRipper#374] opened 2022-05-08 13:35 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.33

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

The console is/was flooded with a lot of Unable to read MonoBehaviour errors, making it look like this. I did "Open Folder" on the game (The Stanley Parable Ultra Deluxe), and then it started importing
![image](https://user-images.githubusercontent.com/23375596/167298716-bd50dae4-e173-4925-8267-1c91cb1543ff.png)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/8647074/AssetRipper.log)

**Comment by ds5678** [comment] 2022-05-08 14:59
Duplicate of #227, #229, and #367

**Closed by ds5678** 2022-05-08 14:59 UTC
Labels: bug

**Comment by pwrmln** [comment] 2022-05-08 19:49
What

**Comment by ds5678** [comment] 2022-05-08 20:01
> What

Your issue is already covered by those other ones. I closed this because duplicate issues make project objectives harder to keep track of.
