### ISSUE TITLE
[Bug]: Not Finishing Download

### ISSUE THREAD

**Issue by znxvx** [AssetRipper/AssetRipper#1584] opened 2024-12-08 01:39 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

VRChat

### Which Unity version did this occur on?

2022.3.22f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

When I try to download my avatar, the process stops at this point and displays an error message.
![Screenshot_2024-12-05_192802](https://github.com/user-attachments/assets/f659aba8-0ba3-4481-ad4e-e5152a44a264)

**Comment by ds5678** [comment] 2024-12-08 01:55
```
An extraction error happened: The filename, directory name, or volume label syntax is incorrect. : 'C:\Users\ggsni\OneDrive\Desktop\SneakersVR\Chat\Avatar\Knight_Alaric\ExportedProject\Assets\Texture2D\z_ColorRampTexGradientTex{_mode__0__colorKeys__{_color__{_r__0.0__g__0.0__b__0.0__a__1.0}__time__0.024170209677839549}_{_color__{_r__0.0__g__0.019170021632871494__b__0.2641509175300598__a__1.0}__time__0.14635054070542909}_{_color__{_r__0.1804379_0.png.meta'

**Comment by ds5678** [comment] 2024-12-08 01:56
Duplicate of #1535

**Closed by ds5678** 2024-12-08 01:56 UTC
Labels: bug
