### ISSUE TITLE
[Bug]: Prefabs (unity ~2018)

### ISSUE THREAD

**Issue by oldsportsgit** [AssetRipper/AssetRipper#739] opened 2023-02-15 14:49 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Baldi's basics classic

### Which Unity version did this occur on?

2018.1.2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

In the unity editor prefabs are looking like white boxes for some odd reason
 if i click on it it shows 0 details about the asset/gameobject why is that?
am i missing something here? is this normal? i don't think so

**Comment by oldsportsgit** [comment] 2023-02-22 14:51
so basically prefabs are "broken" in a way

**Comment by ds5678** [comment] 2023-02-22 19:07
At this time, I'm doing very few (if any) investigations into issues, especially open-ended issues like this one. If you uncover the cause of your problem, I may be more receptive to resolving it. Otherwise, I will likely close or ignore this because of the time commitment involved.

**Comment by ds5678** [comment] 2023-03-03 20:45
I think this was solved in e766a568af6f9fee97694968ac47a72ebc3f1bee. Reopen if you experience otherwise.

**Closed by ds5678** 2023-03-03 20:45 UTC
Labels: bug
