### ISSUE TITLE
[Bug]: AssetRipper wiped a section of my pc

### ISSUE THREAD

**Issue by FunkyShoeMan** [AssetRipper/AssetRipper#761] opened 2023-03-14 20:36 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

ripping blade and socery mod asset

### Which Unity version did this occur on?

2020.3.20f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

A Section of my pc was just wiped when exporting some files 😊 everything in my downloads folder is just gone
![image](https://user-images.githubusercontent.com/111538779/225130259-42ca8840-daf8-466b-8351-74e2d96e3bea.png)

**Comment by ds5678** [comment] 2023-03-14 21:20
Your fault.

**Comment by ds5678** [comment] 2023-03-14 21:20
Duplicate of #738

**Closed by ds5678** 2023-03-14 21:20 UTC
Labels: bug
