### ISSUE TITLE
[Enhancement]: CharacterJoint, ConfigurableJoint, and HingeJoint

### ISSUE THREAD

**Issue by MujeebDawar** [AssetRipper/AssetRipper#358] opened 2022-04-13 07:39 UTC
### Describe the issue

All joints like Character Joint, Configurable Joint, Hinge Joint cannot be exported. They goes to unknown Asset folder.

**Comment by ds5678** [comment] 2022-04-13 07:41
duplicate of #164 which will be done very soon

**Closed by ds5678** 2022-04-13 07:41 UTC
Labels: enhancement, import
