### ISSUE TITLE
[Bug]: Import error

### ISSUE THREAD

**Issue by PadMadoff** [AssetRipper/AssetRipper#1284] opened 2024-04-08 08:57 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Flats (Android\Deleted game from Google Play)

### Which Unity version did this occur on?

4.7.2f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

For some reason it didn't want to import.

### Relevant log output

General : Configuration Settings:
General : ExportRootPath: C:\Users\2skin\OneDrive\Рабочий стол\Unity\AssetRipper\Ripped
General : ScriptContentLevel: Level2
General : StreamingAssetsMode: Extract
General : DefaultVersion: 0.0.0a0
General : BundledAssetsExportMode: GroupByAssetType
General : EnablePrefabOutlining: False
General : EnableStaticMeshSeparation: True
General : EnableAssetDeduplication: True
General : AudioExportFormat: Default
General : ImageExportFormat: Png
General : MeshExportFormat: Native
General : ScriptExportMode: Hybrid
General : ScriptLanguageVersion: AutoSafe
General : ShaderExportMode: Dummy
General : SpriteExportMode: Yaml
General : TerrainExportMode: Yaml
General : TextExportMode: Parse
Import : Attempting to read files from D:\Flats\Data
Import : Game file 'mainData' has been found
Import : Game file 'level0' has been found
Import : Game file 'level1' has been found
System.ArgumentException: An item with the same key has already been added. Key: level1
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T) + 0x14
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey, TValue, InsertionBehavior) + 0x289
   at System.Collections.Generic.Dictionary`2.Add(TKey, TValue) + 0xf
   at AssetRipper.Import.Structure.Platforms.PlatformGameStructure.CollectSerializedGameFiles(DirectoryInfo, IDictionary`2) + 0x19f
   at AssetRipper.Import.Structure.Platforms.MixedGameStructure.CollectFromDirectory(DirectoryInfo, IDictionary`2, IDictionary`2, ISet`1) + 0x41
   at AssetRipper.Import.Structure.Platforms.MixedGameStructure..ctor(IEnumerable`1) + 0x24b
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckMixed(List`1, MixedGameStructure&) + 0x46
   at AssetRipper.Import.Structure.Platforms.PlatformChecker.CheckPlatform(List`1, PlatformGameStructure&, MixedGameStructure&) + 0x19b
   at AssetRipper.Import.Structure.GameStructure..ctor(List`1, CoreConfiguration) + 0x6f
   at AssetRipper.Import.Structure.GameStructure.Load(IEnumerable`1, CoreConfiguration) + 0x35
   at AssetRipper.Export.UnityProjects.ExportHandler.Load(IReadOnlyList`1) + 0x1a3
   at AssetRipper.GUI.Web.GameFileLoader.LoadAndProcess(IReadOnlyList`1) + 0x41
   at AssetRipper.GUI.Web.Pages.Commands.LoadFolder.<AssetRipper-GUI-Web-Pages-ICommand-Execute>d__0.MoveNext() + 0x175
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.Pages.Commands.<HandleCommand>d__6`1.MoveNext() + 0xaf
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb2
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task, ConfigureAwaitOptions) + 0x4b
   at AssetRipper.GUI.Web.ErrorHandlingMiddleware.<InvokeAsync>d__0.MoveNext() + 0x9f

**Comment by PadMadoff** [comment] 2024-04-08 08:59
> Thank you for submitting your first issue here. Please be sure you have uploaded your `AssetRipper.log` file. It is in the same folder as the exe file. :)

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/14903263/AssetRipper.log)

**Comment by ds5678** [comment] 2024-04-08 14:31
You have duplicate files that you're trying to load.

**Comment by ds5678** [comment] 2024-04-13 09:18
Duplicate of #838

**Closed by ds5678** 2024-04-13 09:18 UTC
Labels: bug
