### ISSUE TITLE
[Other]:  Error during reading of asset type Shader

### ISSUE THREAD

**Issue by ZhuGeCold** [AssetRipper/AssetRipper#1543] opened 2024-11-10 08:30 UTC
### Describe the issue

Hi bro,
I had a problem with the new version compiled on October 9. When I tried to extract “Sentimental Death Loop”, I got an error.
```
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(EndianSpanReader&) + 0x20
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList‘1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.ConstantBuffer.ConstantBuffer_2020_3_2.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x6b
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x8f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.ConstantBuffer.ConstantBuffer_2020_3_2.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x6b
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x8f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.ConstantBuffer.ConstantBuffer_2020_3_2.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x6b
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x8f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(EndianSpanReader&) + 0x15
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.ConstantBuffer.ConstantBuffer_2020_3_2.ReadRelease(EndianSpanReader&) + 0x2b
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x6b
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x8f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.MatrixParameter.MatrixParameter.ReadRelease(EndianSpanReader&) + 0x15
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x32
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubProgram.SerializedSubProgram_2021_2_0_a16.ReadRelease(EndianSpanReader&) + 0x99
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0xa6
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Error during reading of asset type Shader. V: 2021.3.9f1 P: StandaloneWinPlayer N: unity default resources Path:
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')
   at AssetRipper.IO.Endian.EndianSpanReader.ReadInt32() + 0x67
   at AssetRipper.SourceGenerated.Subclasses.BufferBinding.BufferBinding_2020_1_0_a14.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedProgramParameters.SerializedProgramParameters.ReadRelease(EndianSpanReader&) + 0x58
   at AssetRipper.SourceGenerated.Subclasses.SerializedPass.SerializedPass_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x8f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedSubShader.SerializedSubShader_2021_2_0_a17.ReadRelease(EndianSpanReader&) + 0x1f
   at AssetRipper.SourceGenerated.Helpers.ReadReleaseMethods.ReadRelease_ArrayAlign_Asset[T](AssetList'1, EndianSpanReader&) + 0x68
   at AssetRipper.SourceGenerated.Subclasses.SerializedShader.SerializedShader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x37
   at AssetRipper.SourceGenerated.Classes.ClassID_48.Shader_2021_2_0_a21.ReadRelease(EndianSpanReader&) + 0x3a
   at AssetRipper.Import.AssetCreation.GameAssetFactory.TryReadNormalObject(AssetInfo, ReadOnlyArraySegment'1, UnityVersion, String&) + 0xca
Import : Unable to read MonoBehaviour Structure, because script UnityEngine.MonoBehaviour layout mismatched binary content (read 228 bytes, expected 236 bytes).
Import : Unable to read MonoBehaviour Structure, because script UnityEngine.MonoBehaviour layout mismatched binary content (read 276 bytes, expected 284 bytes).
```

I don't know if it's because it's not supported yet or if it's my problem.
Also, thank you for your work, it works pretty well most of the time.

**Comment by DatTaiwanGuy** [comment] 2024-11-11 04:24
Try the alpha build of AssetRipper

**Comment by ZhuGeCold** [comment] 2024-11-11 11:55
> Try the alpha build of AssetRipper

Thanks bro. I tried it but got the same error.

**Comment by ds5678** [comment] 2024-11-22 04:02
Those should be warnings (yellow) not errors.

**Comment by ds5678** [comment] 2024-11-22 04:02
Duplicate of #595

**Closed by ds5678** 2024-11-22 04:02 UTC
Labels: import, shaders
