### ISSUE TITLE
[Bug]: [Error] : atlas is not the same as mappedAtlas

### ISSUE THREAD

**Issue by Prota100** [AssetRipper/AssetRipper#1526] opened 2024-10-16 14:02 UTC
### Are you on the latest version of AssetRipper?

No, I need to download a newer version and try again.

### Which release are you using?

Unselected

### Which game did this occur on?

Cult of the Lamb

### Which Unity version did this occur on?

2021.3.16f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

keep getting errors 

### Relevant log output

[EhSSAutD.txt](https://github.com/user-attachments/files/17396923/EhSSAutD.txt)

**Comment by Prota100** [comment] 2024-10-16 14:02
https://pastebin.com/EhSSAutD

**Comment by ds5678** [comment] 2024-11-03 22:28
Duplicate of #740

**Closed by ds5678** 2024-11-03 22:28 UTC
Labels: bug

**Comment by BonecoSinforoso** [comment] 2025-06-03 20:12
The same happened here, in this same game.
