### ISSUE TITLE
[Enhancement]: Set Unity Version

### ISSUE THREAD

**Issue by NomadWithoutAHome** [AssetRipper/AssetRipper#755] opened 2023-03-07 04:58 UTC
### Describe the new feature or enhancement

In Asset Studio, we can set the unity version, i noticed that in both AssetRipper and AssetStudio a bundle i was trying to rip from would not extract and produced errors, so in AssetStudio i was able to set the unity version and that allowed me to extract the bundle just fine, the reason was because the unity version had been stripped from the bundle file i guess, thats the error i got from AssetStudio, i attached the log file from AssetRipper, this happens for all mod bundles.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10905557/AssetRipper.log)

**Comment by ds5678** [comment] 2023-03-07 08:05
Duplicate of #252

**Closed by ds5678** 2023-03-07 08:05 UTC
Labels: enhancement
