### ISSUE TITLE
[Bug]: Not all assets was exported

### ISSUE THREAD

**Issue by Inui-senpai** [AssetRipper/AssetRipper#744] opened 2023-02-21 15:19 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Melissa ❤️ (https://cattrigger.itch.io/melissa-heart)

### Which Unity version did this occur on?

2021.3.1f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

After dragging the "Melissa_Data" folder into the program window, Command Prompt prints some critical errors and warnings. During export process, Command Prompt window shows that the program couldn't export some assets, but the process itself ends successfully.

If it matters, I didn't change any settings in the program window.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/10794884/AssetRipper.log)

**Comment by ds5678** [comment] 2023-02-21 17:26
From what I can see, only a tiny fraction of assets encountered an issue (likely less than 0.1%).

* 2 Materials in unity default resources (Duplicate of #595 )
* 10 Monobehaviours (Duplicate of #647 )

**Closed by ds5678** 2023-02-21 17:26 UTC
Labels: bug
