### ISSUE TITLE
[Bug]: No data left

### ISSUE THREAD

**Issue by Q4st** [AssetRipper/AssetRipper#469] opened 2022-07-18 09:21 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

[apkcombo](https://apkcombo.com/aether-gazer/com.yongshi.tenojo.ys/)

### Which Unity version did this occur on?

2018.4.36f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Import : SerializedFile with name 'cab-1b5ffb86b359e003e46a7d599ab5394c' and path 'C:\Users\Administrator\Desktop\O\b154c278a69c17935cf79bd2dfdf1a92.ys' conflicts with file at 'C:\Users\Administrator\Desktop\O\15c4e84babfe6640cbb45f7a8f472dda.ys'

Error during extraction
”No data left“

![123](https://user-images.githubusercontent.com/58507193/179480971-1e4487bb-17be-4024-9c0a-7b031c6c633c.JPG)

[Bad file link](https://drive.google.com/file/d/1YdqK9ZNngyAt-WrKKy2l4SzwK925UV4P/view?usp=sharing)

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/9130800/AssetRipper.log)

**Comment by ds5678** [comment] 2022-07-19 01:55
Duplicate of #281

**Closed by ds5678** 2022-07-19 01:55 UTC
Labels: bug
