### ISSUE TITLE
[Enhancement]: Add in a option to export assets contained within to the full stored path.

### ISSUE THREAD

**Issue by AraHaan** [AssetRipper/AssetRipper#1289] opened 2024-04-13 09:09 UTC
### Describe the new feature or enhancement

In the program ``AssetStudioModGui v0.17.4.0`` one can select this and it would export the way I want it, however with files that also have ``#some numbers`` in the file names that are duplicate file copies and probably should not be included in the export.

![image](https://github.com/AssetRipper/AssetRipper/assets/15173749/08d2ce26-b8df-4dbb-bf9c-35692b7a7e17)

As such this would be a fine improvement as well. Perhaps also an option to **EXPORT ONLY the Texture2D, Sprite, and text form of entries** as well?

**Comment by ds5678** [comment] 2024-04-13 09:14
> Add in a option to export assets contained within to the full stored path.
> In the program AssetStudioModGui v0.17.4.0 one can select this and it would export the way I want it, however with files that also have #some numbers in the file names that are duplicate file copies and probably should not be included in the export.

Please be more specific about what you want.

> also an option to EXPORT ONLY the Texture2D, Sprite, and text form of entries

That sounds like #504 or #1155.

**Comment by AraHaan** [comment] 2024-04-13 09:30
For example if the resources contains a ``container path`` of say ``sprites/c014/chibi/vstate0`` (Sprite) or say ``images/selectabletile`` (Texture2D) that the name of the item would be exported directly to that folder path in the export folder skipping any "project making" on the exported assets (useful for modding) on games that can load mods using unpacked files to "override" the ones in the resources when loaded.

**Comment by AraHaan** [comment] 2024-04-13 09:35
> > also an option to EXPORT ONLY the Texture2D, Sprite, and text form of entries
> 
> That sounds like #504 or #1155.

Cool that is planned, can't wait to see it arrive soon.

**Comment by ds5678** [comment] 2024-04-13 14:40
Duplicate of #504

**Closed** 2024-04-13 14:40 UTC
Labels: enhancement
