### ISSUE TITLE
[Question]: when i export all files to desktop,my document on desktop are disapeard,and i can't find them.

### ISSUE THREAD

**Issue by Hanjinhou** [AssetRipper/AssetRipper#832] opened 2023-05-21 11:18 UTC
### Question

![20230521-191921](https://github.com/AssetRipper/AssetRipper/assets/30146111/376331f9-cdcc-47f4-af72-5d435dd3fa7c)

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by HeresHavi** [comment] 2023-05-21 14:15
Are you exporting all files into a folder onto your desktop? From the title, it sounds like you are exporting all the files onto the desktop. This is not advised since there's simply just too many files to be extracted.

**Comment by Prosopho** [comment] 2023-05-21 18:25
Duplicate of [#761 ](https://github.com/AssetRipper/AssetRipper/issues/761) 
It was also mentioned on [#738 ](https://github.com/AssetRipper/AssetRipper/issues/738)
I recommend to always export anything into it's own folder to avoid this from happening.

**Comment by ds5678** [comment] 2023-05-23 12:04
Duplicate of https://github.com/AssetRipper/AssetRipper/issues/761

**Closed by ds5678** 2023-05-23 12:04 UTC
