### ISSUE TITLE
[Regression?]: language dropdown completely broken

### ISSUE THREAD

**Issue by JohnCorby** [AssetRipper/AssetRipper#814] opened 2023-04-29 06:33 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

N/A

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

![image](https://user-images.githubusercontent.com/26337121/235287724-c04b249c-a761-4101-ae2c-44c9a0b99a1d.png)

Dropdown is completely blank, but the options are clickable.

**Comment by ds5678** [comment] 2023-04-29 16:33
Duplicate of #801

**Closed by ds5678** 2023-04-29 16:33 UTC
Labels: bug
