### ISSUE TITLE
[Bug]: GLB Export Fails

### ISSUE THREAD

**Issue by 9joao6** [AssetRipper/AssetRipper#1142] opened 2023-12-24 14:04 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest pre-release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

[Lethal Company](https://steamdb.info/app/1966720/)

### Which Unity version did this occur on?

2022.3.9f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Switching the Mesh Export Format from Yaml to GLB, saving the changes, and trying to export Lethal Company's assets causes it to stop abruptly and throws an exception on the log.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13762008/AssetRipper.log)

**Comment by ds5678** [comment] 2023-12-24 16:38
Duplicate of #1132

**Closed by ds5678** 2023-12-24 16:38 UTC
Labels: bug
