### ISSUE TITLE
[Question]: Is there a way too chose the exported unity version?

### ISSUE THREAD

**Issue by JonJon565** [AssetRipper/AssetRipper#970] opened 2023-08-04 15:50 UTC
### Question

Hi ive been having problems with exporting too unity 5 and it has too do with the ui when i open the project in 2017 the ui is fixed but the terrain is messed up (the prefabs actually) so just wondering if its possible too change the version that exports too unity 2017.3.0f3
which is what utiny exports too
i tryed it but its hella old most of the scripts arnt exported but the terrain is i was gunna try too put utiny's scene into the asset rippers scene if you cant export too unity 2017

### Are you sure you want to clutter the issues section?

Yes, I acknowledge that my question may be ignored because I am not following directions.

**Comment by ds5678** [comment] 2023-08-04 18:52
Duplicate of #696

**Closed by ds5678** 2023-08-04 18:52 UTC
