### ISSUE TITLE
[Bug]: Something About Textures on Latest Alpha

### ISSUE THREAD

**Issue by Virjoinga** [AssetRipper/AssetRipper#941] opened 2023-07-26 01:01 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Star Warfare - Alien Invasion HD

### Which Unity version did this occur on?

4.7.2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I pressed export and then it threw out the error, this error did not occur on commit 0148089.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/12166847/AssetRipper.log)

**Comment by ds5678** [comment] 2023-07-26 02:28
Duplicate of #940

**Comment by Virjoinga** [comment] 2023-07-26 03:39
The error was different in the log so I thought it was a different error, my mistake.

**Comment by ds5678** [comment] 2023-07-26 09:40
My mistake

**Closed** 2023-07-26 11:58 UTC
Labels: bug
