### ISSUE TITLE
[Bug]:System.ArgumentOutOfRangeException when extracting from YuGiOh CrossDuel

### ISSUE THREAD

**Issue by SherryChaos** [AssetRipper/AssetRipper#803] opened 2023-04-22 06:19 UTC
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Yu-Gi-Oh! CROSS DUEL
https://play.google.com/store/apps/details?id=jp.konami.crossduel

### Which Unity version did this occur on?

2020.3.36f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

[Error] : Error during reading of asset type AssetBundle. V: 0.0.0f1 P: Android N: cab-8e22c3e60e815b5f10f3aa463f53b52a Path: 
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Can not load this game. AssetStudio alse can not load unless manually input unity version: 2020.3.36f1.

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/11300394/AssetRipper.log)

**Comment by ds5678** [comment] 2023-04-22 12:50
Duplicate of #252

**Closed by ds5678** 2023-04-22 12:50 UTC
Labels: bug
