### ISSUE TITLE
[Other]: Every unity3d asset in Touken Ranbu Pocket loads as an unknown file, making it unable to be opened

### ISSUE THREAD

**Issue by LvNdR1991** [AssetRipper/AssetRipper#863] opened 2023-06-19 20:48 UTC
It's actually a ~500kb PNG with other stuff in it, and I'd like to extract some of the other maps in the game, but I can't, since the game updated to the new version of Unity, and I never got the backgrounds, maps, etc. from it. There's new things in the game that 
   I can't extract because it's just in an format labeled "Unknown", which is actually PNG, (I know because of the headers, etc).
If you could take a look at the archive, and add support for the unity3d contained before a new update is released, that would be greatly appreciated.
                               Thank you!
Below is one of the issue maps.

[adv-battlemap-511-tex.zip](https://github.com/AssetRipper/AssetRipper/files/11792955/adv-battlemap-511-tex.zip)

**Comment by ds5678** [comment] 2023-06-20 02:09
Duplicate of #252

**Closed by ds5678** 2023-06-20 02:09 UTC

**Comment by LvNdR1991** [comment] 2023-06-20 17:43
Sorry, I still can't get it to work.

**Comment by ds5678** [comment] 2023-06-20 19:12
You misunderstand. I did not close your issue because it was solved. I closed your issue because there was already another issue describing your problem, making yours redundant.

**Comment by LvNdR1991** [comment] 2023-06-20 22:18
Ah, sorry.
